@comet/create-app run lint autofix
vivid-planet/comet-starter pull request #154
Opened 2024-02-05 08:08 UTC by max-debug022

ReplacePlaceholder now uses lint autofix after the content is replaced to ensure correct file formatting. This functionality was also added to the removeShowcase function.

2024-02-05 08:31 UTC, nsams commented on create-app/src/util/lintText.ts
> +        cwd: __dirname,
__dirname is `.../create-app/src/util`, I don't think that is what you want.

https://www.geeksforgeeks.org/difference-between-process-cwd-and-__dirname-in-node-js/

2024-02-05 08:57 UTC, max-debug022 commented on create-app/src/util/lintText.ts
> +        cwd: __dirname,
We need that here because of the behavior of the package. Eslint uses the projects eslint-config. As the config uses an external source (extends from @comet/eslint-config) this leads to an error, when the dependencies are not installed (this is the case for the initial create-app). To avoid this, eslint now uses the eslint-config of itself.

2024-02-05 09:43 UTC, thomasdax98 commented
@max-debug022 Is there a reason why we don't just execute the lint scripts as a last step? (like https://github.com/vivid-planet/comet-upgrade/pull/9/files) Since I didn't review the script initially, I'm not 100% familiar with how it's structured.

2024-02-05 11:35 UTC, nsams commented on create-app/src/util/lintText.ts
> +        cwd: __dirname,
I understand, please add a comment explaining this

2024-02-06 12:57 UTC, max-debug022 commented
> @max-debug022 Is there a reason why we don't just execute the lint scripts as a last step? (like https://github.com/vivid-planet/comet-upgrade/pull/9/files) Since I didn't review the script initially, I'm not 100% familiar with how it's structured.

@thomasdax98 That is a good idea - I will implement that.

2024-02-09 08:40 UTC, thomasdax98 commented on create-app/src/index.ts
> +        .option("-ni, --no-install", "Disables the automatic installation of dependencies.")
Please also add the new option to the readme

2024-02-09 08:40 UTC, thomasdax98 commented on create-app/src/scripts/create-app/createApp.ts
> +    runEslintFix();
I think `createInitialGitCommit();` should be done after `runEslintFix();`. Now the `lang.ts` file is fixed but I have to manually add a second commit

<img width="528" alt="Bildschirmfoto 2024-02-09 um 09 39 35" src="https://github.com/vivid-planet/comet-starter/assets/13380047/2c710450-b0f3-43b3-8bb8-adf598e479d0">

2024-02-09 08:54 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +    runEslintFix();
Yes you are right, but with install.sh, the husky pre-commit hook is also installed which requires the .git folder (which is deleted in the cleanup process) 

I think I might have to split the function up and make the commit afterwards

2024-02-12 08:10 UTC, max-debug022 commented on create-app/src/index.ts
> +        .option("-ni, --no-install", "Disables the automatic installation of dependencies.")
Fixed in: https://github.com/vivid-planet/comet-starter/pull/154/commits/2c3207d4944032ed0b913e7503d7ae11f5c61db8

2024-02-12 08:11 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +    runEslintFix();
Fixed in: https://github.com/vivid-planet/comet-starter/pull/154/commits/3c6549a0b1525f78ead6dfc8518c59d09c1c451e

2024-02-13 12:27 UTC, johnnyomair commented
@max-debug022 could you please rebase this PR now that #159 has been merged? Thanks!

2024-02-13 12:42 UTC, max-debug022 commented
> @max-debug022 could you please rebase this PR now that #159 has been merged? Thanks!

@johnnyomair done!

2024-02-19 09:01 UTC, johnnyomair requested changes

2024-02-19 09:17 UTC, max-debug022 commented on create-app/src/scripts/remove-showcase/removeShowcase.ts
> +        let fileContent = readFileSync(content.file, "utf-8").toString();
Yes, you are right - but in this instance, only the files in `contentToRemove` will be read. Setting the BufferEncoding was done to ensure that the file is read and interpreted as a UTF-8 encoded string explicitly.

2024-02-19 09:45 UTC, max-debug022 commented on create-app/src/util/runEslintFix.ts
> +            if (microservice !== "api") execSync(`npm --prefix ${microservice} run lint:prepare`);
What would the prepare script do for api?

2024-02-19 10:02 UTC, max-debug022 commented on create-app/src/util/runEslintFix.ts
> +    console.log("Fixing ESLint errors");
I removed the message [here](https://github.com/vivid-planet/comet-starter/pull/154/commits/faf285b6bfa8e6399fb77f377560fc51758af462) since I don't think this message improved the script anyway. For instance, in create-app it will likely not be seen since it is printed before the "whats next"-messages.

2024-02-19 10:33 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
I tried to fix that issue, but I am not able to. My approach was configuring the child process with a killSignal as recommended in the node docs but this does not seem to work.

@nsams maybe you know another way to implement that?

2024-02-19 12:03 UTC, nsams commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
I thought this is not an issue, as the child process also gets the SIGINT signal sent if you hit Ctrl+C.

Did you test tist?

2024-02-19 12:23 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
Yes, the activity monitor indicated that the install.sh process **remained active** even after terminating it with Ctrl+C. However, it eventually stopped after 10-15 secs, which is too little time to complete the installation of all dependencies.

2024-02-20 07:20 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
Yes thats possible. Anyways, after some more testing https://github.com/vivid-planet/comet-starter/pull/154/commits/b553afdf88a66fe57d764e804b26c8d3fcd4134e works.

2024-02-20 07:44 UTC, nsams commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
TLDR: your change is not needed, please revert

killSignal changes the signal sent to the child process when the parent process sends a kill signal because of timeout (if configured) or abort signal (if configured) ([reference](https://nodejs.org/api/child_process.html#child_processexecsynccommand-options)) 

Both are not used in your case and the SIGINT is sent by the terminal where you press Ctrl+C to both processes.

I made a simple test:
```
niko@niko:~/dev/killtest$ cat parent.js
const { execSync } = require("child_process");
execSync("node child.js > child.log 2>&1");
niko@niko:~/dev/killtest$ cat child.js 
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))

process.on('SIGINT', () => {
    console.log("child caught SIGINT, exiting");
    process.exit();
});
process.on('SIGTERM', () => {
    console.log("child caught SIGTERM, exiting");
    process.exit();
});


async function main() {
    console.log('child sleeping for 10 seconds...');
    await delay(10000);
    console.log('child exiting');
}
main();
niko@niko:~/dev/killtest$ node parent.js
^C
niko@niko:~/dev/killtest$ cat child.log 
child sleeping for 10 seconds...
child caught SIGINT, exiting
```

here you see that:
- child process gets SIGINT signal and exits right after pressing Ctrl+C
- it gets SIGINT without having to specify killSignal

2024-02-20 09:20 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
Done - thank you for clarifying. I appreciate your explanation and code example very much, it helped me to understand the killSignals better. 

Nevertheless, I noticed some strange (most likely not strange, but I don't understand why) behaviors: When adding the killSignal-option, there was only one npm install process. If I am correct, there should be three, as of the install.sh script, which uses the & operator for parallelization. (There are three instances without the option)

2024-02-20 10:13 UTC, nsams commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
The killSignal option has no effect if you don't use timeout option or abort signal option.

You might be right with the & in install.sh, as that creates background processes that _might_ not get the Ctrl+C SIGINT. killSignal doesn't change that though. Is the & worth it anyway?

2024-02-20 11:32 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
I measured the time for both variants and it does not make a difference. And ctrl+c also works without the killSignal for both variants (It just takes about 15 more seconds)

2024-02-20 12:51 UTC, nsams commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
then I would remove the & to simplify things

2024-02-21 11:13 UTC, johnnyomair commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
> I measured the time for both variants and it does not make a difference

Did you try this on fresh copies? I can't believe that running the npm installs in parallel doesn't make a difference 🤔

2024-02-21 11:14 UTC, johnnyomair commented on create-app/src/util/runEslintFix.ts
> +            if (microservice !== "api") execSync(`npm --prefix ${microservice} run lint:prepare`);
You're right, haven't thought about that

2024-02-21 12:13 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
Yes, I did. I believe this issue is caused by the significantly longer duration of the admin installation compared to the quicker api and site installations. Therefore, when the 'install.sh' script waits for the completion of the admin script, it's almost as if the installations are being done sequentially. On top of that, differences in the download speed add "noise" in the duration, making it such that no noticeable difference is can be seen.

2024-02-21 16:43 UTC, johnnyomair commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
Okay, then remove the "optimization" please 😁

2024-02-22 09:42 UTC, thomasdax98 commented on create-app/src/util/hasDependenciesInstalled.ts
> +    return (packageJson.includes("dependencies") || packageJson.includes("devDependencies")) && fs.existsSync("node_modules");
In line 8 you use the absolute path
```
 const packageJson = fs.readFileSync(`${process.cwd()}/${microservice}/package.json`, "utf8");
```
here you use the relative path
```
fs.existsSync("node_modules");
```
Are you sure this works as expected?

2024-02-22 09:45 UTC, thomasdax98 commented on create-app/src/util/hasDependenciesInstalled.ts
> +    return (packageJson.includes("dependencies") || packageJson.includes("devDependencies")) && fs.existsSync("node_modules");
otherwise lgtm

2024-02-22 09:52 UTC, thomasdax98 commented
And please resolve the conflicts

2024-02-22 09:53 UTC, nsams commented on create-app/src/util/hasDependenciesInstalled.ts
> +    return (packageJson.includes("dependencies") || packageJson.includes("devDependencies")) && fs.existsSync("node_modules");
that is practically the same, although `${process.cwd()}/` could be omitted

2024-02-22 10:54 UTC, max-debug022 commented on create-app/src/scripts/create-app/createApp.ts
> +            execSync("sh ./install.sh");
Changed in: https://github.com/vivid-planet/comet-starter/pull/154/commits/7a52dd70c0909e2c16a9c740349c4614e0bd72d0

2024-02-22 11:00 UTC, max-debug022 commented on create-app/src/util/hasDependenciesInstalled.ts
> +    return (packageJson.includes("dependencies") || packageJson.includes("devDependencies")) && fs.existsSync("node_modules");
Yes, it works. I prefer the absolute path when changing non-project files because:
- Readability/Clarity
- Error Prevention
- Avoidance of Ambiguity

2024-02-22 11:39 UTC, dkarnutsch commented on admin/package.json
> +        "lint:prepare": "npm run intl:compile && run-p gql:types generate-block-types",
if you don't want to this manually, you can use https://docs.npmjs.com/cli/v10/using-npm/scripts#life-cycle-scripts

2024-02-22 12:54 UTC, thomasdax98 approved these changes

2024-02-22 13:35 UTC, max-debug022 commented on create-app/src/util/hasDependenciesInstalled.ts
> +    return (packageJson.includes("dependencies") || packageJson.includes("devDependencies")) && fs.existsSync("node_modules");
Oh that's what you meant - Sorry I misunderstood that. No in that case you are right, I intended to check for the microservices node_modules (root also has some, so it works anyway)

2024-02-22 14:41 UTC, max-debug022 commented on admin/package.json
> +        "lint:prepare": "npm run intl:compile && run-p gql:types generate-block-types",
Fixed in: https://github.com/vivid-planet/comet-starter/pull/154/commits/b2f5f2f0f0aef7d5aed4fd4e88c9116571516e77

2024-02-22 14:41 UTC, max-debug022 commented on create-app/src/util/hasDependenciesInstalled.ts
> +    return (packageJson.includes("dependencies") || packageJson.includes("devDependencies")) && fs.existsSync("node_modules");
Solved in: https://github.com/vivid-planet/comet-starter/pull/154/commits/d4b5176b4e155f41d1d49ad510d2b65c88052088

2024-02-22 15:07 UTC, johnnyomair commented on admin/package.json
> +        "lint:prepare": "npm run intl:compile && run-p gql:types generate-block-types",
This doesn't really change much, since you still need to call `prelint` manually before running ESLint 🤔

2024-02-22 15:08 UTC, johnnyomair commented
@max-debug022 please fix the failing pipeline

2024-02-22 15:19 UTC, max-debug022 commented on admin/package.json
> +        "lint:prepare": "npm run intl:compile && run-p gql:types generate-block-types",
But now it's the recommended way - isn't that preferable?

2024-02-22 15:22 UTC, johnnyomair commented on admin/package.json
> +        "lint:prepare": "npm run intl:compile && run-p gql:types generate-block-types",
Of course. I'd still prefer if we could remove the manual run and the check for api in `runEslintFix` somehow

2024-02-22 15:23 UTC, johnnyomair approved these changes

2024-02-22 15:38 UTC, thomasdax98 approved these changes

2024-02-22 16:13 UTC, dkarnutsch approved these changes

2024-02-22 16:28 UTC, nsams approved these changes

2024-02-22 17:13 UTC, merged