Allow Prettier in IDE for microservices
vivid-planet/comet-starter pull request #169
Opened 2024-02-23 12:33 UTC by fraxachun

https://github.com/vivid-planet/comet-starter/pull/95#issue-2064259483

Fixes the "bad IDE support" by allowing allowing prettier in IDE for api/admin/site/create-app but executing the cli-check only for root-files.

2024-02-26 07:48 UTC, dkarnutsch requested changes

2024-02-26 07:48 UTC, dkarnutsch commented on package.json
> -        "lint:root": "npx prettier --check './**/*.{js,json,md,yml,yaml}'",
This does not work for values.yaml in chart/.

We would need to exclude admin/api/site/create-app manually.

2024-02-26 14:18 UTC, nsams commented on package.json
> +        "lint:root": "npx prettier --check './!(admin|api|site|create-app)/**/*.{js,json,md,yml,yaml}'",
now that this doesn't lint root alone anymore, maybe rename to:
```suggestion
        "lint:prettier": "npx prettier --check './!(admin|api|site|create-app)/**/*.{js,json,md,yml,yaml}'",
```

2024-02-26 14:19 UTC, nsams commented on package.json
> +        "lint:root": "npx prettier --check './!(admin|api|site|create-app)/**/*.{js,json,md,yml,yaml}'",
or, wait: des the `!` mean those will be excluded?

2024-02-26 14:42 UTC, nsams commented on package.json
> +        "lint:root": "npx prettier --check './!(admin|api|site|create-app)/**/*.{js,json,md,yml,yaml}'",
ok, so why this change? does it still fix "bad IDE support"?

2024-02-26 15:20 UTC, nsams approved these changes

2024-02-28 08:15 UTC, johnnyomair approved these changes
Finally, thanks!

2024-02-28 08:16 UTC, johnnyomair commented
@dkarnutsch please review again, thanks!

2024-02-28 09:04 UTC, dkarnutsch approved these changes

2024-02-28 09:16 UTC, thomasdax98 approved these changes

2024-02-28 09:17 UTC, merged