Fix intl update
vivid-planet/comet-starter pull request #17
Opened 2023-09-13 09:22 UTC by max-debug022

2023-09-14 07:24 UTC, dkarnutsch requested changes

2023-09-14 07:24 UTC, dkarnutsch commented on admin/intl-update.sh
> +git clone https://github.com/vivid-planet/comet-starter-lang.git lang/starter-lang
what about comet messages?

2023-09-21 13:38 UTC, thomasdax98 commented on .github/workflows/lint.yml
> +          path: "site/lang/starter-lang"
@dkarnutsch Is it a good idea to clone the translations here?

It looks to me like this was done in a postinstall script in the old starter. That seems simpler to me because you don't have to treat the pipeline and dev environment (./install.sh) separately.

2023-10-02 07:40 UTC, dkarnutsch approved these changes

2023-10-02 07:58 UTC, nsams approved these changes

2023-10-02 09:11 UTC, thomasdax98 approved these changes

2023-10-02 11:17 UTC, merged