add custom css reset and css normalize to fix some of the most common…
vivid-planet/comet-starter pull request #180
Opened 2024-03-04 08:39 UTC by martinrohrmoser

… issues with default styles

2024-03-04 12:52 UTC, jamesricky requested changes

2024-03-04 12:52 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +    }
This issue also affects `button`. 
Maybe combine this with the selector above:

```css
button,
input,
select,
textarea {
    /* Change the font styles in all browsers. */
    font: inherit;
    font-size: 100%;

    /* Adjust form border for iOS Safari */
    border-radius: 0;
}
```

2024-03-04 12:52 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +        font-size: 100%;
Does `font-size: 100%` do anything, when `font: inherit` is set? 🤔

2024-03-04 12:52 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +    */
Since this selector does other things as well, maybe move this comment above the relevant lines. 
Also `margin: 0` is pretty self-explanatory, probably unnecessary mention in the comment. 
Comments should generally explain why something is done, not what it does. 

```css
body {
    margin: 0;
    font-family: sans-serif;
    font-weight: 400;
    
    /* Prevent font size adjustments after orientation changes in mobile devices */
    -webkit-text-size-adjust: none;

    /* Improve text rendering with font-smoothing */
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

2024-03-04 12:52 UTC, jamesricky commented on site/src/pages/_app.page.tsx
>          font-weight: 400;
Isn't `font-weight: 400` the default value in all browsers anyway? 

```suggestion
```

2024-03-04 14:46 UTC, nsams commented on site/src/pages/_app.page.tsx
> +    */
> Comments should generally explain why something is done, not what it does.

yep :+1:

2024-03-04 15:02 UTC, martinrohrmoser commented on site/src/pages/_app.page.tsx
>          font-family: sans-serif;
@jamesricky While this may be true, I think it's better to set a `font-family` to make it look better "out of the box".

2024-03-04 15:50 UTC, jamesricky commented on site/src/pages/_app.page.tsx
>          font-family: sans-serif;
I don't see the point in overriding a value, that has to be overridden again anyway...
If it's wrong and looks good, it's still wrong. Just harder for us to see that it's wrong.

2024-03-04 15:55 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +        /* Change the font styles in all browsers. */
This is self-explanatory, please explain why this is done or remove the comment.

2024-03-04 15:55 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +        /* adjust form border for iOS */
```suggestion
        /* Remove default border-radius that is added by iOS Safari */
```

2024-03-04 15:55 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +    /* Remove default margin from headlines and text */
This is self-explanatory, please explain why this is done or remove the comment.

2024-03-05 06:01 UTC, martinrohrmoser commented on site/src/pages/_app.page.tsx
>          font-family: sans-serif;
@mariokemetinger What's your opinion on this matter? I would really like to set `font-family: sans-serif;`, because for me, it serves it's intended purpose.

2024-03-05 06:52 UTC, mariokemetinger commented on site/src/pages/_app.page.tsx
>          font-family: sans-serif;
@martinrohrmoser i think there shouldn't be a default font-family because you easily overlook some not correct styled parts like form stuff, which required font-family on their own (props for the font inherit 👍).

2024-03-05 11:04 UTC, johnnyomair commented on site/src/pages/_app.page.tsx
> +        -webkit-text-size-adjust: 100%;
Why set it here when it's overridden in body?

2024-03-05 11:04 UTC, johnnyomair commented on site/src/pages/_app.page.tsx
> +    /* this fixes a problem with flexbox and avoids overflows https://defensivecss.dev/tip/flexbox-min-content-size/ */
```suggestion
    /* Fix a problem with Flexbox to avoid overflows: https://defensivecss.dev/tip/flexbox-min-content-size/ */
```

2024-03-05 11:04 UTC, johnnyomair commented on site/src/pages/_app.page.tsx
> +    */
Please add more context here, maybe a link to the guide where you took it from?

2024-03-05 11:04 UTC, johnnyomair commented on site/src/pages/_app.page.tsx
> +        /* inherit font to apply the webs default font for form elements */
```suggestion
        /* Use the application's default font for form elements */
```

2024-03-05 11:04 UTC, johnnyomair commented on site/src/pages/_app.page.tsx
> +    /* Prevent sub and sup elements from affecting the line height in all browsers. */
```suggestion
    /* Prevent sub and sup elements from affecting the line height in all browsers */
```

2024-03-05 11:04 UTC, johnnyomair commented on site/src/pages/_app.page.tsx
> +        Prevent adjustments of font size after orientation changes in iOS.
```suggestion
        Prevent adjustments of font size after orientation changes in iOS
```

Nit: Either use proper punctuation everywhere, or don't use it at all 😁

2024-03-07 15:08 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +        Fore more info please check out https://www.joshwcomeau.com/css/custom-css-reset/#eight-root-stacking-context-9
```suggestion
        For more info please check out https://www.joshwcomeau.com/css/custom-css-reset/#eight-root-stacking-context-9
```

2024-03-11 15:21 UTC, johnnyomair commented on site/src/pages/_app.page.tsx
> +        For more info please check out https://www.joshwcomeau.com/css/custom-css-reset/#eight-root-stacking-context-9
```suggestion
        Create a root stacking context: https://www.joshwcomeau.com/css/custom-css-reset/#eight-root-stacking-context-9
```

IMO this is enough

2024-03-13 11:10 UTC, jamesricky approved these changes

2024-03-18 14:30 UTC, mariokemetinger commented
@martinrohrmoser add also the `width: 100vw`  and `overflow-x: hidden` on body to get the same amount of pixel when using vw or percent: https://codepen.io/MarioKemetinger/pen/xxBJWrm

2024-03-19 09:54 UTC, johnnyomair submitted a review, later dismissed

2024-03-19 11:46 UTC, mariokemetinger submitted a review, later dismissed

2024-03-19 13:25 UTC, thomasdax98 submitted a review, later dismissed

2024-03-19 14:58 UTC, jamesricky requested changes

2024-03-19 14:58 UTC, jamesricky commented on site/src/pages/_app.page.tsx
> +        overflow-x: hidden
@mariokemetinger @martinrohrmoser this causes elements with `width: 100%` to be cut off on the side with the scrollbar. 

The red `:before` and `:after` have the same width but the one on the right is barely visible: https://jsfiddle.net/rickysmith/qpuy6bL7/ 

<img width="1213" alt="Screenshot 2024-03-19 at 15 55 52" src="https://github.com/vivid-planet/comet-starter/assets/6264317/ab228a5a-33b3-4aee-b645-3a8d7e228c0d">

This seems to me like the root cause of many confusing bugs in the future...

2024-03-20 07:15 UTC, jamesricky approved these changes

2024-03-20 07:30 UTC, johnnyomair approved these changes

2024-03-20 07:33 UTC, mariokemetinger approved these changes

2024-03-20 07:48 UTC, merged