Add remove-showcase script
vivid-planet/comet-starter pull request #23
Opened 2023-09-21 10:42 UTC by max-debug022

# @comet/remove-showcase

This is a command-line script to remove the showcase from a Comet project.

## Usage

To run the script, use the following command:

```
npx @comet/remove-showcase
```

Example usage:

```
npx @comet/remove-showcase
```

2023-09-22 09:36 UTC, nsams commented on scripts/remove-showcase/package.json
> +        "eslint-plugin-unused-imports": "^0.1.3",
please cleanup dependencies and remove those you don't directly use

2023-09-22 09:36 UTC, nsams approved these changes

2023-10-02 07:45 UTC, dkarnutsch approved these changes

2023-10-02 07:56 UTC, nsams submitted a review, later dismissed

2023-10-05 15:20 UTC, nsams submitted a review, later dismissed

2023-10-10 06:44 UTC, nsams submitted a review, later dismissed

2023-10-10 09:20 UTC, johnnyomair requested changes

2023-10-10 09:20 UTC, johnnyomair commented on create-app/src/scripts/remove-showcase/src/removeShowcase.ts
> +function deleteFilesAndFolders(files: string[]) {
Why not use util/deleteFilesAndFolders?

2023-11-16 10:16 UTC, johnnyomair commented
@max-debug022 please rebase

2023-11-27 11:19 UTC, dkarnutsch submitted a review, later dismissed

2023-11-27 12:32 UTC, nsams commented
you should also check for comet project in cwd like in removeSite

2023-11-27 12:45 UTC, max-debug022 commented
> you should also check for comet project in cwd like in removeSite

I've moved the cwdIsCometProject function inside the utils folder so it can be used for both scripts

2023-11-27 12:52 UTC, nsams submitted a review, later dismissed

2023-11-29 16:05 UTC, max-debug022 commented
I am sorry - I ran into trouble resolving the conflicts due to some strange behaviors. By mistake, I squashed all commits. I hope this does not cause confusion. Since this is a small PR I hope you don't mind.

2023-11-30 07:21 UTC, nsams approved these changes

2023-11-30 07:52 UTC, johnnyomair approved these changes
Could you please remove the additional `src/` folder in `src/scripts/` in a follow-up PR? I believe this is a leftover from when those scripts were separate packages...

IMO `src/scripts/removeShowcase.ts` is enough (also for `removeSite.ts`)

2023-11-30 07:53 UTC, merged