@comet/create-app: Add `remove-site` command
vivid-planet/comet-starter pull request #24
Opened 2023-09-21 12:00 UTC by max-debug022

Add `remove-site` command to remove the site from a Comet project.

Example usage:

```bash
npx @comet/create-app remove-site
```

2023-10-05 07:59 UTC, nsams commented on scripts/remove-site/src/removeSite.ts
> +    removeReference("dev-pm.config.js", /{[\n ]*name: "[Ss][Ii][Tt][Ee].*},\n/gs);
you can use the ignore case modifier instead:
```suggestion
    removeReference("dev-pm.config.js", /{[\n ]*name: "site.*},\n/gsi);
```

2023-10-05 07:59 UTC, nsams commented on scripts/remove-site/src/removeSite.ts
> +    removeReference(".env", /.*[Ss][Ii][Tt][Ee].*\n/gm);
admin/.env and api/.env are a symlink to .env

2023-10-05 08:01 UTC, nsams commented
I'm not entirely sure if we decided on this:

this should be a sub command of create-app, usage:

`npx @comet/create-app remove-site`

2023-10-05 15:19 UTC, nsams commented
you should not use the branch of another PR as target, because as soon as the other PR gets merged this one is dangling.

usually we let both target main (with the downside that the second also contains the commits from the first)

2023-10-05 15:19 UTC, nsams submitted a review, later dismissed

2023-10-09 05:19 UTC, max-debug022 commented
> you should not use the branch of another PR as target, because as soon as the other PR gets merged this one is dangling.
> 
> usually we let both target main (with the downside that the second also contains the commits from the first)

Thank you for the information - I did not know that. Should I change this back to main?

2023-10-09 05:55 UTC, nsams commented
yes

2023-10-09 07:03 UTC, nsams submitted a review, later dismissed

2023-10-09 07:04 UTC, nsams commented
(obviously you must wait with merge this until dependent PR ist merged)

2023-10-09 09:13 UTC, max-debug022 commented
> (obviously you must wait with merge this until dependent PR ist merged)

Yes oc.

2023-10-10 06:44 UTC, nsams submitted a review, later dismissed

2023-10-10 09:22 UTC, johnnyomair requested changes

2023-10-10 09:22 UTC, johnnyomair commented on create-app/src/scripts/remove-site/src/removeSite.ts
> +function removeFilesAndFolders() {
Please use deleteFilesAndFolders for this

2023-11-16 10:16 UTC, johnnyomair commented
@max-debug022 please rebase

2023-11-16 15:59 UTC, nsams commented on create-app/src/util/replacePlaceholder.ts
> +    const placeholder = /[comet-]?[Ss]tarter/g;
please don't make unrelated changes to the topic of a Pull Request

2023-11-16 16:02 UTC, johnnyomair commented on create-app/src/util/replacePlaceholder.ts
> +    const placeholder = /[comet-]?[Ss]tarter/g;
Why is this necessary at all?

2023-11-17 07:30 UTC, max-debug022 commented on create-app/src/util/replacePlaceholder.ts
> +    const placeholder = /[comet-]?[Ss]tarter/g;
thank you for noticing, this is an artifact from rebasing and squashing.

2023-11-21 13:53 UTC, johnnyomair requested changes

2023-11-21 13:53 UTC, johnnyomair commented on create-app/README.md
> +```
```suggestion
```bash
```

2023-11-21 13:53 UTC, johnnyomair commented on create-app/src/scripts/remove-site/src/removeSite.ts
> +function deleteFilesAndFolders() {
We should already have a util function for this 🤔

2023-11-21 13:53 UTC, johnnyomair commented on create-app/src/scripts/remove-site/src/removeSite.ts
> +    deleteFilesAndFolders();
This is not a sync function, so you need to await the result

2023-11-23 10:35 UTC, max-debug022 commented on create-app/src/createApp.ts
> +            removeSite();
So, how could we do that? While a checksum would typically be a fitting solution, the diversity of Comet projects makes this impractical.

My ideas are:
- Examining the data of specific configuration files related to Comet projects.
- Analyzing the naming conventions of key project files or directories.
- Scanning for unique identifiers or metadata within project files that indicate Comet integration.
- Reviewing the project's version control history for markers of Comet-related changes.
- Checking for specific cli commands or configurations associated with Comet in project scripts.

While these methods provide alternative approaches for confirming the cwd as a Comet project, none of them can guarantee it, imo.

2023-11-23 10:46 UTC, max-debug022 commented on create-app/src/scripts/remove-site/src/removeSite.ts
> +function deleteFilesAndFolders() {
we have

2023-11-23 15:01 UTC, max-debug022 commented on create-app/src/createApp.ts
> +            removeSite();
This seems quite inappropriate since I put much thought into what and how to respond to your concerns. I respect and value your qualified opinions/concerns and hold them in high regard. Reading that your time is too precious for reading mine is offensive.  
In addition, I want to point out that my comments are not AI-generated. Nevertheless, I use tools to reformulate my ideas and thoughts in order to avoid misunderstandings that could be caused by my original formulations. In my opinion, this does not render my ideas any less valuable or the time it takes to read them less precious. 

The only intention was to clarify my formulations if you disagree with that approach I will avoid it from now on. (fyi this comment is neither ai-generated nor is it reformulated and I hope your time is not too precious to read it)

2023-11-23 16:06 UTC, nsams commented on create-app/src/createApp.ts
> +            removeSite();
Let's be constructive:

- you could check `api/src/comet-config.json` for existance, tough this file was introduced in v4 it should exist in all new projects starting with our starter
- or you could check `src/api/package.json` or `src/admin/package.json` for any `@comet/*` packages

The first seems good enough to me and simple to implement

2023-11-27 10:16 UTC, nsams submitted a review, later dismissed

2023-11-27 11:20 UTC, dkarnutsch submitted a review, later dismissed

2023-11-27 13:07 UTC, johnnyomair approved these changes

2023-11-28 11:33 UTC, dkarnutsch approved these changes

2023-11-28 14:30 UTC, merged