Columns block, page layout
vivid-planet/comet-starter pull request #257
Opened 2024-06-07 06:01 UTC by SebiVPS

---

## PR Checklist

-   [x] Link to the respective task if one exists: COM-834
-   [x] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>
<img width="1824" alt="Screenshot 2024-06-07 at 07 58 35" src="https://github.com/vivid-planet/comet-starter/assets/42858722/02e163e0-af6b-4b8c-861d-2700aea81e9d">

<img width="607" alt="Screenshot 2024-06-07 at 07 58 49" src="https://github.com/vivid-planet/comet-starter/assets/42858722/fd666e04-85c3-43d0-84c7-4f6b94621932">

<img width="1289" alt="Screenshot 2024-06-07 at 07 12 02" src="https://github.com/vivid-planet/comet-starter/assets/42858722/1c797fef-36b8-4a1b-b4d2-f975b9cdae63">

</details>

2024-06-10 07:28 UTC, nsams commented on site/src/layout/GlobalStyles.ts
> +        ${gridColumnsCSSVars()};
could you explain those variables? And why is defaultMaxWidth a css variable?

2024-06-10 07:28 UTC, nsams commented on site/src/documents/pages/blocks/PageContentBlock.tsx
> +    richtext: (props) => <RichTextBlock data={props} addPageGridLayoutStyle />,
why does a richtext block need a PageGridLyout nd other blocks not?

2024-06-10 07:28 UTC, nsams commented on admin/src/common/blocks/ColumnsContentBlock.tsx
> +        space: SpaceBlock,
shouldn't there be almost all PageContent blocks?

2024-06-10 07:55 UTC, SebiVPS commented on site/src/layout/GlobalStyles.ts
> +        ${gridColumnsCSSVars()};
@mariokemetinger  can explain you these variables in detail. (https://codepen.io/MarioKemetinger/pen/xxBJWrm) (also see COM-714)

You are right, the defaultMaxWidth must not be a css variable, it is implemented in another project this way, but it do not see why. I'll change that 👍

2024-06-10 07:56 UTC, SebiVPS commented on site/src/documents/pages/blocks/PageContentBlock.tsx
> +    richtext: (props) => <RichTextBlock data={props} addPageGridLayoutStyle />,
The other block are not refactored yet. Just added the merged HeadingBlock right now.

2024-06-10 07:56 UTC, SebiVPS commented on admin/src/common/blocks/ColumnsContentBlock.tsx
> +        space: SpaceBlock,
The other block are not refactored yet. Just added the merged HeadingBlock right now.

2024-06-10 08:04 UTC, nsams commented on site/src/layout/GlobalStyles.ts
> +        ${gridColumnsCSSVars()};
yes, please explain the ideas behind this

2024-06-10 08:05 UTC, SebiVPS commented on site/src/documents/pages/blocks/PageContentBlock.tsx
> +    heading: (props) => <HeadingBlock data={props} addPageGridLayoutStyle />,
@nsams @mariokemetinger @jamesricky @johnnyomair 
An alternative i thought about, was to add a wrapping div with the pageGridLayoutStyle here, instead of adding it in the blocks inside. 
Technically it would be cleaner to add it here. What do you think?

2024-06-10 09:08 UTC, SebiVPS commented on site/src/layout/GlobalStyles.ts
> +        ${gridColumnsCSSVars()};
Just discussed this topic with @mariokemetinger, we are going to remove these variables for now from the starter. 👍

2024-06-10 12:29 UTC, nsams commented
Isn't this still moving the positioning of blocks into the blocks? (as in https://github.com/vivid-planet/comet-starter/pull/255#issuecomment-2152076950)

2024-06-10 12:35 UTC, SebiVPS commented
> Isn't this still moving the positioning of blocks into the blocks? (as in [#255 (comment)](https://github.com/vivid-planet/comet-starter/pull/255#issuecomment-2152076950))

It is, the only other solution would be something like that:
https://github.com/vivid-planet/comet-starter/pull/257#discussion_r1632775336

I talked to Mario earlier today, he thinks it is ok. But we can discuss this point. What do you think?

2024-06-10 12:46 UTC, nsams commented on site/src/documents/pages/blocks/PageContentBlock.tsx
> +    heading: (props) => <HeadingBlock data={props} addPageGridLayoutStyle />,
yes! Or a wrapper around PageContentBlock.

2024-06-10 15:13 UTC, nsams commented on site/src/documents/pages/blocks/PageContentBlock.tsx
> +    heading: (props) => <HeadingBlock data={props} addPageGridLayoutStyle />,
> but not practicable because there are use-cases (eg. background-color) for blocks which need to be set for the full width

please try to include an block in this PR where this use-case is actually used

2024-06-11 08:04 UTC, SebiVPS commented on site/src/util/PageGridLayoutStyle.ts
> +export const pageGridLayoutStyle = css`
Thats all whats left.

2024-06-11 14:06 UTC, nsams commented on site/src/components/common/ConditionalPageGridLayout.tsx
> +export const ConditionalPageGridLayout = ({ pageGridLayout, gridColumn, children }: ConditionalPageGridLayoutProps) => {
One component that does based on props as 3 different things: not easy to use/understand.

I would prefer something simple: for example a GridRoot component and a GridColumn component.

2024-06-12 07:46 UTC, SebiVPS commented on site/src/components/common/ConditionalPageGridLayout.tsx
> +export const ConditionalPageGridLayout = ({ pageGridLayout, gridColumn, children }: ConditionalPageGridLayoutProps) => {
Yes you are right, something like that would optimize the usage and outsource the conditional rendering, but would be too difficult to understand/use.
I refactored once again to a simple GridRoot, which can we put into the PageContentBlock in comet v7 (then we do not need the conditional render in the blocks).
I think thats the best solution i can think of atm. Maybe we can come up with something magic i the todays discussion.

2024-06-12 12:04 UTC, jamesricky commented on site/src/components/common/GridRoot.ts
> +    box-sizing: border-box;
```suggestion
```

2024-06-14 06:12 UTC, jamesricky commented on site/src/common/blocks/CallToActionListBlock.tsx
> +    grid-column: 3 / 23;
I would prefer `3 / -3`. Makes it easier to see that it's centered / indented symmetrically. 
Also this would still work if `grid-template-columns` is changed to some other value. 

_(same for the other blocks)_

 ```suggestion
     grid-column: 3 / -3;
```

2024-06-14 06:12 UTC, jamesricky commented on site/src/common/blocks/CallToActionListBlock.tsx
> +const GridColumn = styled.div`
Since this is explicitly used only for the `PageContent` maybe this should be reflected in the name, rather than naming it after the used css property...

Maybe: `PageLayoutContent`, `PageIndentation`, `PageContentIndentation` 🤔 

_(same for the other blocks)_

2024-06-17 06:46 UTC, jamesricky approved these changes

2024-06-18 09:23 UTC, johnnyomair requested changes

2024-06-18 09:23 UTC, johnnyomair commented on site/src/common/blocks/CallToActionListBlock.tsx
> +import { PageLayout } from "@src/components/common/PageLayout";
Please move this file to either `src/common/PageLayout` or `src/layout/PageLayout`. In Starter we group files by feature (products, pages, common), not by type (hooks, components)

2024-06-18 09:23 UTC, johnnyomair commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
This doesn't seem right to me... Could you please further explain? What about adding two columns in a one-column-layout? In our projects, we usually showed them underneath.

2024-06-18 09:23 UTC, johnnyomair commented on site/src/common/blocks/ColumnsContentBlock.tsx
> +    { label: "Column" },
```suggestion
    { label: "Columns" },
```

2024-06-18 09:23 UTC, johnnyomair commented on site/src/components/common/PageLayout.tsx
> +interface PageLayoutProps extends PropsWithChildren<HTMLAttributes<HTMLDivElement>> {
I believe PropsWithChildren is redundant here

2024-06-18 09:23 UTC, johnnyomair commented on site/src/components/common/PageLayout.tsx
> +    </Root>
```suggestion
export const PageLayout = ({ grid, ...restProps }: PageLayoutProps) => (
    <Root $grid={grid} {...restProps} />
```

2024-06-18 09:48 UTC, johnnyomair reviewed
Please resolve conflicts

2024-06-18 09:54 UTC, SebiVPS commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
I tried to simplify the usage of the columnGrid map.

> What about adding two columns in a one-column-layout? In our projects, we usually showed them underneath.

As far as i know there are no plans in wrapping a column layout in another column layout. 
If that is really needed one has to refactor this component completely,  an additional logic is also needed to get the information whats the parent columns layout?

2024-06-18 10:05 UTC, SebiVPS commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
I think, found the perfect solution: using the modulo operator it can be ensured that the additional columns block are rendered underneath:
<img width="1013" alt="Screenshot 2024-06-18 at 12 04 25" src="https://github.com/vivid-planet/comet-starter/assets/42858722/609c00fb-22f4-4cc6-b5a8-a4e8e285a3c3">

2024-06-18 10:07 UTC, SebiVPS commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
`$column={columnGrid[index % Object.keys(columnGrid).length][layout]}`

that line is indeed a bit hard to read 🤔  maybe you have a suggestion to improve the readability?

2024-06-18 10:20 UTC, SebiVPS commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
Ok, i was wrong, modulo is not the right choice, it does not work for all cases. I'll think about it after lunch 🤔

2024-06-18 10:58 UTC, SebiVPS commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
With an additional map, where i have access to the column count it is possible with the modulo operator 👍 
What do you think about this solution? Is there a way to improve this a bit more?

2024-06-18 14:56 UTC, johnnyomair commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
Tried it myself in #262. IMO this is a cleaner solution, what do you think?

2024-06-19 06:16 UTC, SebiVPS commented on site/src/common/blocks/ColumnsBlock.tsx
> +                    const gridColumn = index === 0 ? column1Grid[layout] : column2Grid[layout];
Yes 👍  that looks a lot cleaner.

2024-06-19 06:42 UTC, johnnyomair submitted a review, later dismissed
LGTM.

2024-06-19 14:24 UTC, johnnyomair approved these changes

2024-06-20 08:06 UTC, jamesricky approved these changes

2024-06-20 08:25 UTC, merged