Update/Add security headers
vivid-planet/comet-starter pull request #280
Opened 2024-06-26 14:54 UTC by max-debug022

This PR improves/updates the HTTP-Headers
---
<tldr>
**TLDR**
- Update helmet to 7.1.0 in API and Admin
- Coherent CORS-Policy (Cross-Origin-Ressource-Sharing) for the API -> to Admin & Site
- Coherent CORP/COEP (Cross-Origin-Ressource/Embedder-Policy) for API, Admin & Site
- Strict COOP (Cross-Origin-Opener-Policy) for API, Admin & Site
- Removal of deprecated, redundant, or prohibited headers
- CSP (Content Security Policy) that enforces the JEA (just enough access) principle 
</tldr>
<details>
This PR implements the "Just-Enough-Access" (JEA) security strategy, ensuring that only necessary privileges are granted while restricting all others. The PR includes a coherent Cross-Origin Resource Sharing (CORS) policy to ensure resources can only be shared within the microservices. Additionally, Cross-Origin Resource Policy (CORP) and Cross-Origin Embedder Policy (COEP) have been enforced to control resource access and embedding to authorized origins only. Several Content Security Policy (CSP) errors have been resolved & unnecessary privileges have been removed - Admin has slightly more flexibility than the Site.

- Update helmet to v7.1.0
- CORS uses now a maxAge of 600s as Chromium (prior to v76) caps at 10mins 
- CORP only for Same-Site
- Set COOP for same-origin
- Remove the empty exposedHeaders field as it is the default
- Disable unused x-powered-by header
- Disable [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) X-XSS-Protection Header
- Disable [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) X-Frame-Options Header
- Enable HSTS with recommended values 
- Disable Referrer Policy 
...
</details>

2024-07-01 07:36 UTC, thomasdax98 commented
Did you test this in one of our projects in a deployed setting? I fear that there might be some unwanted side-effects relating to different domains in a deployed setting

2024-07-01 07:43 UTC, max-debug022 commented
> Did you test this in one of our projects in a deployed setting? I fear that there might be some unwanted side-effects relating to different domains in a deployed setting

Yes, I tested it on deployed settings.

2024-07-01 08:38 UTC, dkarnutsch commented
> Did you test this in one of our projects in a deployed setting? I fear that there might be some unwanted side-effects relating to different domains in a deployed setting

I would not add this to existing projects without extensive testing. However, the starter can define best practices and hopefully all bugs are discovered during development. So I think it is relatively safe to merge this.

2024-07-01 08:39 UTC, dkarnutsch commented
Some header could possible have a comment, when to extend/change them.

2024-07-01 10:26 UTC, max-debug022 commented
> Some header could possible have a comment, when to extend/change them.
> 
> You could also add links to best practices (MDN?), so we can track changes.

Luckily I originally added comments to each Header but removed them since I wasn't sure if comments should be in the code. I could add them, but I think it would be better to add detailed docs on how to modify each header and what effect each header has. What would you prefer?

2024-07-01 10:46 UTC, dkarnutsch commented
> > Some header could possible have a comment, when to extend/change them.
> > You could also add links to best practices (MDN?), so we can track changes.
> 
> Luckily I originally added comments to each Header but removed them since I wasn't sure if comments should be in the code. I could add them again, but I think it would be better to add detailed docs on how to modify each header and what effect each header has. What would you prefer?

In code, as documentation can drift away. @johnnyomair?

2024-07-04 14:28 UTC, johnnyomair commented
> > > Some header could possible have a comment, when to extend/change them.
> > > You could also add links to best practices (MDN?), so we can track changes.
> > 
> > 
> > Luckily I originally added comments to each Header but removed them since I wasn't sure if comments should be in the code. I could add them again, but I think it would be better to add detailed docs on how to modify each header and what effect each header has. What would you prefer?
> 
> In code, as documentation can drift away. @johnnyomair?

Agreed. We could add line comments for each header/item.

2024-07-04 14:29 UTC, johnnyomair commented on site/next.config.js
>                  },
Why is it okay to remove this?

2024-07-07 14:33 UTC, thomasdax98 commented on site/next.config.js
> +                    // https://developer.mozilla.org/en-US/docs/Web/Security/IFrame_credentialless
```suggestion
                    // This value should be set to 'require-corp' as soon as iframe credentialless is supported by all browsers
                    // https://developer.mozilla.org/en-US/docs/Web/Security/IFrame_credentialless
                    // https://caniuse.com/mdn-html_elements_iframe_credentialless
```

2024-07-07 14:34 UTC, thomasdax98 commented on site/next.config.js
>                  },
Is "none" even a valid value? It's not mentioned on MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin

2024-07-07 14:52 UTC, thomasdax98 commented on site/next.config.js
> +                    value: "same-site",
Why `same-site` instead of `same-origin`?

2024-07-07 14:52 UTC, thomasdax98 commented on api/src/main.ts
> +            },
Doesn't this limit the access to the API to our API domain? 

I believe we have some client projects where at least API and site use different domains

2024-07-07 14:53 UTC, thomasdax98 commented on site/next.config.js
> +                    value: "same-site",
Ah I guess it's because same-site allows different sub domains

2024-07-08 06:13 UTC, max-debug022 commented on site/next.config.js
>                  },
@johnnyomair  Since this site should only be embedded as an iframe, focusing on CORP/COEP makes sense for security, and it doesn’t need to handle cross-origin requests. Therefore, removing the admin url in Access-Control-Allow-Origin should be ok because CORS mainly hanldes cross-origin data access, typically for APIs.

@thomasdax98 Given that ACAO is unnecessary, we have three options: omit it, set it to an invalid value, or use "none". I prefer setting it to "none" or omitting it entirely. This is because the default behavior for ACAO in Next.js isn’t explicitly documented, and relying on defaults that could change over time isn’t ideal imho.

2024-07-08 06:20 UTC, max-debug022 commented on admin/server/server.js
>          xXssProtection: false,
It’s just a personal preference to explicitly set values even if they are implicitly set by default. This way, anyone looking at the code doesn't need to refer to the documentation to understand the defaults. Plus, if the default behavior ever changes, our explicitly set values ensure our application’s behavior remains the same.

2024-07-08 06:39 UTC, max-debug022 commented on admin/server/server.js
> +        xFrameOptions: false,
Because it is obsoleted by frame-ancestors: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options

But since frame-ancestors has no fallback, I think we should specify this directive and set it to none or self.

2024-07-08 06:49 UTC, max-debug022 commented on admin/server/server.js
> +        xDownloadOptions: true,
Changed in: https://github.com/vivid-planet/comet-starter/pull/280#discussion_r1668052908

2024-07-08 06:54 UTC, max-debug022 commented on admin/server/server.js
> +        xFrameOptions: false,
https://github.com/vivid-planet/comet-starter/pull/280/commits/3221d1ac1eadf4a7e48a8fc85565e258b946234f

2024-07-08 06:55 UTC, max-debug022 commented on api/src/app.module.ts
> +                            maxAge: 600,
1) Reduced Preflight Requests
2) Improved performance by caching preflight requests

2024-07-08 06:56 UTC, max-debug022 commented on site/next.config.js
> +                        "script-src 'unsafe-eval'",
Unfortunately, it seems like it is required by one of our dependencies.

2024-07-08 06:59 UTC, max-debug022 commented on site/next.config.js
> +                    value: "same-site",
Subdomains but most importantly ports.

2024-07-08 07:00 UTC, max-debug022 commented on api/src/main.ts
> +            },
> Doesn't this limit the access to the API to our API domain?
Exactly

> I believe we have some client projects where at least API and site use different domains
We would need to change it in the client project.

2024-07-08 07:53 UTC, max-debug022 commented
> Agreed. We could add line comments for each header/item.

@johnnyomair what headers should be documented and how? I don't think an explanation is useful since anyone can look headers up and they are fairly well explained. And if you understand the header you probably understand the logic behind their value. 

For example. x-xss-protection - the first thing in the MDN docs is that it should not be used, so its value is false.

2024-07-08 09:02 UTC, thomasdax98 commented on admin/server/server.js
>          xXssProtection: false,
> This way, anyone looking at the code doesn't need to refer to the documentation to understand the defaults.

Especially in this case, I'd say it's confusing for someone who isn't very familiar with the headers. XSS protection sounds like a good thing, so people might wonder why we are disabling it. It's not implicit that this header is actually bad. So this will prompt people to consult the docs even more. 

> Plus, if the default behavior ever changes, our explicitly set values ensure our application’s behavior remains the same.

Since this is an outdated, non-standard, harmful header, it's not a realistic scenario that the default ever changes to true. If anything, the header will be removed. While I'm normally also a fan of explicit configuration, I wouldn't say this really applies here.

But let's see what the others think about that

2024-07-08 09:06 UTC, thomasdax98 commented
> Edit: My initial documentation was somewhat like this:
> 
> ```
> app.use(
>   helmet({
>     contentSecurityPolicy: {
>       directives: {
>         "default-src": ["'none'"], // No external resources are needed
>       },
>       useDefaults: false, // Disable all other default CSP rules
>     },
>     xXssProtection: false, // Disable deprecated header
>     xFrameOptions: false, // Disable deprecated header
>     crossOriginResourcePolicy: "same-origin", // Do not allow cross-origin requests to access the response
>     crossOriginEmbedderPolicy: true, // =no-corp Enable COEP
>     crossOriginOpenerPolicy: true, // =same-origin Enable COOP
>     strictTransportSecurity: {
>       // Enable HSTS
>       maxAge: 63072000, // 2 years (recommended if including subdomains)
>       includeSubDomains: true, // Include all subdomains
>       preload: true, // Enable HSTS preload
>     },
>     referrerPolicy: {
>       policy: "no-referrer", // No referrer information needs to be sent
>     },
>     xContentTypeOptions: true, // = nosniff
>     xDnsPrefetchControl: false, // Disable non-standard header as recommended by MDN
>     xDownloadOptions: true, // = noopen (forces IE8+ not to open files in the context of the page but instead download them)
>     xPermittedCrossDomainPolicies: true, // = none (prevent the browser from MIME-sniffing)
>     originAgentCluster: true, // = false (disables the agent cluster)
>   }),
> );
> ```

@max-debug022 I like this. During the review I had a hard time wrapping my head around "What does `true` (or `false`) mean in this case?"

I think you should add these comments

2024-07-08 10:12 UTC, max-debug022 commented
I added the comments: https://github.com/vivid-planet/comet-starter/pull/280/commits/cbc047256c8285d648e77fa165b158a0abd119cb

2024-07-08 10:15 UTC, max-debug022 commented on admin/server/server.js
>          xXssProtection: false,
I noticed that false (= not send the header) is not the default value - "0" is. So removed the header since the default value of 0 is actually better than not setting it at all

2024-07-09 08:39 UTC, thomasdax98 approved these changes

2024-07-11 13:46 UTC, johnnyomair commented on site/next.config.js
>                  },
@max-debug022 but is "none" a valid value?

2024-07-11 13:46 UTC, johnnyomair commented on site/next.config.js
As discussed, please also disable x-powered-by here

2024-07-22 10:35 UTC, johnnyomair approved these changes

2024-08-01 11:28 UTC, max-debug022 commented
@thomasdax98 @fraxachun @thomasdax98 @johnnyomair

2024-08-05 13:24 UTC, dkarnutsch commented on admin/server/server.js
> +                upgradeInsecureRequests: [],
this is not consistent with the site (where this prop is missing),
also: this prop is not working with our domain setup (dani.dev.vivid-planet.cloud)

2024-08-06 05:49 UTC, max-debug022 commented on admin/server/server.js
> +                upgradeInsecureRequests: [],
Added with: https://github.com/vivid-planet/comet-starter/pull/280/commits/31542001b14f22273959b9c30dc9db30fe87c471

2024-08-06 07:16 UTC, johnnyomair commented on site/next.config.js
> +                        "upgrade-insecure-requests", // Remove this option when working with the Domain-Setup
This should be done automatically based on the presence of the environment variable.

2024-08-08 10:47 UTC, johnnyomair commented on site/next.config.js
> +                        "upgrade-insecure-requests", // Remove this option when working with the Domain-Setup
I guess you'll need the same fix in the Admin and API, right?

2024-08-20 06:02 UTC, max-debug022 commented on site/next.config.js
> +                        "upgrade-insecure-requests", // Remove this option when working with the Domain-Setup
Yes: https://github.com/vivid-planet/comet-starter/pull/280/commits/7afbbf331528aea4ef10069e4625d7ce4f180fb8

2024-08-20 06:02 UTC, max-debug022 commented on site/next.config.js
> +                        `frame-src https://www.youtube-nocookie.com; ${!process.env.DEV_DOMAIN ? "upgrade-insecure-requests" : ""}`, // Don't use upgrade-insecure-requests with the Domain-Setup
https://github.com/vivid-planet/comet-starter/pull/280/commits/7afbbf331528aea4ef10069e4625d7ce4f180fb8

2024-09-09 14:18 UTC, johnnyomair commented
@max-debug022 please fix conflicts.

2024-09-10 06:27 UTC, max-debug022 commented on site/next.config.js
> +                        "script-src 'unsafe-eval'",
Well, it's a lot; and I do not know an efficient way to evaluate it (even with tools like bundle-analyzer). Just because a package contains eval or any other "unsafe-eval" code doesn't necessarily mean the CSP needs to permit it. We have hundreds of files (including package dependencies oc) that include some form of eval.

A few example-deps are:
- exceljs
- protobufjs
- next.js
- terser-webpack-plugin
- uglify-js

There are many others, particularly code minifiers, TypeScript dependencies, and linting libraries. Has anyone suggestions on a more effective way to evaluate this?

2024-09-10 06:34 UTC, johnnyomair commented on site/next.config.js
> +                        "script-src 'unsafe-eval'",
> Has anyone suggestions on a more effective way to evaluate this?

I'd probably set it to 'none', start the site and see where an error occurs.

> exceljs

I doubt that we have this dependency in the site

2024-09-10 06:58 UTC, max-debug022 commented on site/next.config.js
> +                        "script-src 'unsafe-eval'",
> I'd probably set it to 'none', start the site and see where an error occurs.
That's what I did in the first place, but the error messages are generic and rarely inform you about the specific package.
> I doubt that we have this dependency in the site
Yes, sorry - I forgot to mention that I included all microservices since we not only use the CSP in the site, (although API wouldn't be necessary I guess).

2024-09-11 08:13 UTC, johnnyomair commented on site/next.config.js
> +                        "script-src 'unsafe-eval'",
We can have a look at it together the next time we're both in the office.

2024-10-08 07:24 UTC, johnnyomair commented on site/next.config.js
> +                        `img-src 'self' data: ${process.env.API_URL}/`,
I believe we don't need the API_URL here anymore since we're using a rewrite to proxy the images through the site: #298

2024-10-17 11:14 UTC, johnnyomair requested changes
Please fix the lint workflow

2024-10-22 05:55 UTC, johnnyomair submitted a review, later dismissed

2024-10-22 05:55 UTC, johnnyomair commented
@dkarnutsch @fraxachun @thomasdax98 please review, this one's been open for way too long 😁

2024-10-28 07:45 UTC, max-debug022 commented on site/next.config.js
> -                                frame-ancestors ${process.env.ADMIN_URL};
Yes thats true: https://github.com/vivid-planet/comet-starter/pull/280/commits/e7050c55f36d686e059540befcf4e662c15dab71

2024-10-28 07:46 UTC, max-debug022 commented on site/next.config.js
> +                        `${process.env.NODE_ENV === "development" ? "" : "upgrade-insecure-requests"}`, // Don't use upgrade-insecure-requests with the Domain-Setup
What do you think about this: https://github.com/vivid-planet/comet-starter/pull/280/commits/42a5ebfdd8c5ea5aff990f0fb72124c5336a6151

2024-10-28 07:46 UTC, max-debug022 commented on site/next.config.js
> +                        `img-src data: 'self' ${process.env.NODE_ENV === "development" ? process.env.API_URL + "/" : ""}`,
Fixed in: https://github.com/vivid-planet/comet-starter/pull/280/commits/42a5ebfdd8c5ea5aff990f0fb72124c5336a6151

2024-10-28 10:18 UTC, johnnyomair commented on site/next.config.js
> +function generateCSP() {
headers already is a function, so why not move the code there before returning the array?

2024-10-30 09:44 UTC, max-debug022 commented on site/next.config.js
> +        cspRules["upgrade-insecure-requests"] = ""; // Don't use upgrade-insecure-requests with Domain-Setup
This instructs user agents to treat a site's insecure URLs (HTTP) as though they have been replaced with secure URLs.

2024-11-05 15:39 UTC, max-debug022 commented
I will wait for this PR to be merged: https://github.com/vivid-planet/comet-starter/pull/415

2024-11-05 15:44 UTC, max-debug022 commented on site/next.config.js
> +        cspRules["upgrade-insecure-requests"] = ""; // Don't use upgrade-insecure-requests with Domain-Setup
Including upgrade-insecure-requests is optional but helps avoid potential misconfigurations and adds an extra layer of security, so I’d recommend keeping it.

2025-01-23 11:32 UTC, thomasdax98 submitted a review, later dismissed

2025-01-27 06:57 UTC, dkarnutsch commented on api/package.json
> -        "graphql": "^15.10.1",
why? this seems unrelated to this PR

2025-01-27 08:11 UTC, johnnyomair commented on api/package.json
> -        "graphql": "^15.10.1",
Also, this shouldn't be removed.

2025-01-27 08:12 UTC, johnnyomair requested changes

2025-01-27 08:12 UTC, johnnyomair commented on api/project-words.txt
Please remove this file

2025-01-27 08:12 UTC, johnnyomair commented on site/next.config.mjs
> +                    //
```suggestion
```

2025-02-18 14:47 UTC, johnnyomair approved these changes

2025-02-19 08:25 UTC, johnnyomair commented on site/src/middleware/contentSecurityPolicyHeaders.ts
> +    { directive: "img-src", values: ["'self'", "data:", process.env.API_URL?.replace("/api", "") ?? ""] },
@max-debug022 can we remove the API_URL? The string replacement of /api is odd IMO.

2025-02-19 08:26 UTC, johnnyomair commented
> Shouldn't it be comet-demo first?

This PR has been started long before we changed to demo first, so I'd like to finish it here and then copy it to Demo

2025-02-19 09:08 UTC, dkarnutsch approved these changes

2025-02-20 09:25 UTC, max-debug022 commented on site/src/middleware/contentSecurityPolicyHeaders.ts
> +    { directive: "img-src", values: ["'self'", "data:", process.env.API_URL?.replace("/api", "") ?? ""] },
We need this for images in the block-preview iframe:
![image](https://github.com/user-attachments/assets/efa1821d-2307-4813-8063-51c68319f2a7)
![image](https://github.com/user-attachments/assets/891310b9-158e-435b-8a8b-aac737ca5d9c)

2025-02-20 11:29 UTC, thomasdax98 approved these changes

2025-02-20 11:35 UTC, merged