Add basic Footer
vivid-planet/comet-starter pull request #282
Opened 2024-07-01 12:15 UTC by jomunker

---

This adds a basic footer, which can be configured in the admin. The footer customization can be found under `Project Snips/Footer`.

## PR Checklist

-   [x] Link to the respective task if one exists: COM-872
-   [x] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>
    

### Mobile
<img width="400" alt="Screenshot 2024-07-01 at 14 10 05" src="https://github.com/vivid-planet/comet-starter/assets/56400587/dc356946-bd3f-4f5d-b2dd-c8d8d3677b23">

### Tablet
<img width="953" alt="Screenshot 2024-07-01 at 14 09 58" src="https://github.com/vivid-planet/comet-starter/assets/56400587/92ebfc1d-6f0e-44f4-9c7e-1e3ff90522fb">

### Laptop
<img width="1424" alt="Screenshot 2024-07-01 at 14 09 50" src="https://github.com/vivid-planet/comet-starter/assets/56400587/4a088d2d-4587-4e55-82da-91bb98384758">

### Desktop
<img width="1780" alt="Screenshot 2024-07-01 at 14 09 43" src="https://github.com/vivid-planet/comet-starter/assets/56400587/bc56a1c7-912c-49c3-9b58-425a9f730378">

</details>

2024-07-01 12:43 UTC, jomunker commented
- [ ] Add preview functionality

2024-07-08 07:22 UTC, johnnyomair commented on api/src/footers/dto/footer-content-scope.ts
> +export class FooterContentScope {
Slightly off-topic, but something I noticed recently: For the page tree content scope we have `PageTreeNodeScope` (without content). Should we do the same for all scopes?

2024-07-08 07:22 UTC, johnnyomair commented on admin/src/footers/EditFooterPage.tsx
> +    }, [data, scope]);
```suggestion
    }, [data]);
```

2024-07-08 07:22 UTC, johnnyomair commented on admin/src/footers/EditFooterPage.tsx
> +            contentScope: scope,
Optional: I'd name the query arg `scope`

2024-07-08 07:22 UTC, johnnyomair commented on admin/src/footers/EditFooterPage.tsx
@nsams this is a lot of code for a rather simple form. We should start investing into the Admin Generator for content-driven applications

2024-07-08 07:22 UTC, johnnyomair commented on site/src/layout/footer/Footer.tsx
> +function Footer({ footer }: Props): JSX.Element {
```suggestion
function Footer({ footer }: Props) {
```

Will be inferred

2024-07-08 07:22 UTC, johnnyomair commented on site/src/layout/Layout.tsx
> +`;
Is this necessary to always render the footer at the bottom? @mariokemetinger is this how we should do this?

2024-07-08 07:22 UTC, johnnyomair commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    }
Should the image really be positioned with absolute positioning? Isn't there a better way?

2024-07-09 06:46 UTC, mariokemetinger commented on site/src/layout/Layout.tsx
> +`;
@johnnyomair I think it is. This is a legit way to do this i think. Only thing that is not ideal is that the `margin-top: auto` positioning of the footer is in the Footer-Content Block itself. Normally this should also happen in Layout, but because it is the footer and not like a ListItem Block i am okay with it.

2024-07-09 06:50 UTC, mariokemetinger commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    }
@johnnyomair we made this solution together and i think this is the best way to do it without having like a 2nd ImageWrapper for mobile or something...

2024-07-12 12:07 UTC, jomunker commented on api/src/footers/dto/footer-content-scope.ts
> +export class FooterContentScope {
To whom is this question directed?

2024-07-12 12:10 UTC, jomunker commented on admin/src/footers/EditFooterPage.tsx
> +            contentScope: scope,
you mean `footerQuery`?

2024-07-15 06:44 UTC, johnnyomair commented on api/src/footers/dto/footer-content-scope.ts
> +export class FooterContentScope {
I thought maybe the other reviewers might chime in... But maybe we need to discuss this in a separate PR

2024-07-15 06:45 UTC, johnnyomair commented on admin/src/footers/EditFooterPage.tsx
> +            contentScope: scope,
Yes, the argument in footerQuery

2024-07-24 07:35 UTC, jomunker commented on api/src/footers/dto/footer-content-scope.ts
> +export class FooterContentScope {
Resolve this thread then?

2024-07-25 10:45 UTC, jomunker commented on admin/src/footers/EditFooterPage.tsx
> +            contentScope: scope,
https://github.com/vivid-planet/comet-starter/commit/f3a65aba604ee7370ccbe8d23c73edfc5cd67205

2024-07-25 10:45 UTC, jomunker commented on api/src/footers/dto/footer-content-scope.ts
> +export class FooterContentScope {
https://github.com/vivid-planet/comet-starter/pull/282/commits/a7e5eb390c60fd7647030af8d3688460bbc0c602

2024-07-29 13:04 UTC, johnnyomair commented on site/src/app/[lang]/[[...path]]/layout.tsx
> +import * as React from "react";
This isn't needed anymore. @SebiVPS even removed it in other places 😁

2024-07-29 13:04 UTC, johnnyomair commented on site/src/layout/footer/Footer.tsx
> +import * as React from "react";
```suggestion
```

2024-07-29 13:04 UTC, johnnyomair commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    margin-top: auto;
Is this necessary? 🤔

2024-07-31 11:48 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    margin-top: auto;
Jup. Otherwise the footer will stick to the top. With that, it'll stay at the bottom

2024-07-31 11:48 UTC, jomunker commented on site/src/app/[lang]/[[...path]]/layout.tsx
> +import * as React from "react";
Good to know 👍🏻

2024-07-31 11:51 UTC, jomunker commented on site/src/layout/footer/Footer.tsx
> +import * as React from "react";
https://github.com/vivid-planet/comet-starter/pull/282/commits/2c203795eff21a0d54f535c6e59947a226c7dde1

2024-07-31 11:52 UTC, jomunker commented on site/src/app/[lang]/[[...path]]/layout.tsx
> +import * as React from "react";
https://github.com/vivid-planet/comet-starter/pull/282/commits/2c203795eff21a0d54f535c6e59947a226c7dde1

2024-08-01 06:23 UTC, johnnyomair submitted a review, later dismissed

2024-08-08 10:13 UTC, jomunker commented
@mariokemetinger @johnnyomair @nsams @fraxachun @dkarnutsch @thomasdax98 
Please check this PR 🙂

2024-08-12 08:49 UTC, thomasdax98 commented on admin/src/footers/EditFooterPage.tsx
> +    }, [data]);
When adding a footer for the first time, the SaveButton is never disabled:

https://github.com/user-attachments/assets/3bf4bf49-3481-45af-8bc8-48b0c2050a24

I guess this is because the Apollo cache contains null for the footer. Since it has no id, it can't merge the result of the mutation in the existing cache entry. You could fix this by 

either running a refetch query (could look something like this:)

```ts
const [update, { loading: saving, error: hasSaveErrors }] = useMutation<GQLSaveFooterMutation, GQLSaveFooterMutationVariables>(
    saveFooterMutation,
    { refetchQueries: !data?.footer ? [namedOperations.Query.Footer] : [] },
);
```

or manually overriding the cache: https://www.apollographql.com/docs/react/data/mutations/#updating-the-cache-directly

2024-08-12 08:52 UTC, thomasdax98 commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                    </ImageWrapper>
The image looks strange when empty because the skeleton is so tall:

<img width="960" alt="Bildschirmfoto 2024-08-12 um 10 27 51" src="https://github.com/user-attachments/assets/d8b420fd-337a-47b6-94f4-0f1b37b98789">

The height is hardcoded in the library: https://github.com/vivid-planet/comet/blob/4f32ad014d092e37214e7f03d9c07a0c1dd444b5/packages/site/cms-site/src/previewskeleton/PreviewSkeleton.sc.ts#L45

Maybe we can override this here? Or change it in the library to be more flexible? @jamesricky @johnnyomair What do you think?

2024-08-12 11:25 UTC, jamesricky commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                    </ImageWrapper>
We could add a required `aspectRatio` prop for the `media` type, since we probably always need it for `DamImageBlock` anyway.

2024-08-13 12:12 UTC, johnnyomair reviewed
Please resolve conflicts.

2024-08-13 14:08 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                        <DamImageBlock data={image} aspectRatio="1/1" objectFit="contain" />
```suggestion
                        <DamImageBlock data={image} aspectRatio="1/1" style={{ object-fit="contain" }} />
```

the prop `objectFit` is deprecated by next/image, you should set the style.

2024-08-13 14:14 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    padding: 60px 16px;
```suggestion
    padding: 60px ${({ theme }) => theme.spacing.D100};
```

maybe you can use a value from the spacings here?

2024-08-13 14:18 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    gap: 30px;
```suggestion
    gap: ${({ theme }) => theme.spacing.S600};
```

here also? try to use as much as possible from the spacings please.

2024-09-09 15:21 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                    </ImageWrapper>
@thomasdax98 @johnnyomair Whats is your opinion here?

2024-09-09 16:32 UTC, jomunker commented on admin/src/footers/EditFooterPage.tsx
> +    }, [data]);
https://github.com/vivid-planet/comet-starter/pull/282/commits/8965957e74ee22ece70acf86167570584af1d644

2024-09-09 16:32 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    padding: 60px 16px;
https://github.com/vivid-planet/comet-starter/pull/282/commits/19ddced1ce8a8eb24c6c8d21c915b6952149b36d

2024-09-10 06:38 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    margin: 19px 0 35px; /* 19px since element in RTE has margin bottom of 16px */
You can disable the margin bottom in the RTE with `disableLastBottomSpacing`

2024-09-10 06:38 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +import * as React from "react";
Please check this PR, the react barrel imports are not need and allowed anymore. (The pipeline also fails)

2024-09-10 06:38 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    font-family: ${({ theme }) => theme.fontFamily};
no need to set the fontFamily, when you use the Typography

2024-09-11 08:12 UTC, johnnyomair commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                        <DamImageBlock data={image} aspectRatio="1/1" style={{ objectFit: "contain" }} />
@SebiVPS is this the way we should to this?

2024-09-11 08:12 UTC, johnnyomair commented on admin/src/footers/EditFooterPage.tsx
> +        { refetchQueries: !data?.footer ? [namedOperations.Query.Footer] : [] },
Shouldn't this be updated in the Apollo Cache automatically? Maybe we're missing an `id` here?

2024-09-11 08:17 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                        <DamImageBlock data={image} aspectRatio="1/1" style={{ objectFit: "contain" }} />
Yes, looks good 👍

2024-09-11 12:33 UTC, jomunker commented on admin/src/footers/EditFooterPage.tsx
> +        { refetchQueries: !data?.footer ? [namedOperations.Query.Footer] : [] },
https://github.com/vivid-planet/comet-starter/pull/282#discussion_r1713381087

2024-09-11 12:52 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    font-family: ${({ theme }) => theme.fontFamily};
It actually is. It looks like this if i remove it:
<img width="337" alt="image" src="https://github.com/user-attachments/assets/f7ff3710-aab8-40f9-b05b-9a8bbe657ee1">

2024-09-11 12:54 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +import * as React from "react";
https://github.com/vivid-planet/comet-starter/pull/282/commits/027809959beee07a09a992e7341926588bb6edad

2024-09-11 12:54 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    margin: 19px 0 35px; /* 19px since element in RTE has margin bottom of 16px */
Thanks for the hint!

https://github.com/vivid-planet/comet-starter/pull/282/commits/e7f1e569829f63800391718125371e790a5d9632

2024-09-16 08:22 UTC, jamesricky commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +        place-self: start center;
Does this do anything, with `position: absolute`?

2024-09-16 08:22 UTC, jamesricky commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +        transform: translate(-50%, -50%);
Absolute positioning will cause the image to overlay the text content

<img width="1133" alt="image" src="https://github.com/user-attachments/assets/410fec7f-428c-4184-bc2a-b44cafae5d27">

2024-09-16 08:22 UTC, jamesricky commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +export const FooterContentBlock = withPreview(
Long text will cause the `ImageTextWrapper` to overlay the `LinkCopyrightWrapper`

<img width="1229" alt="image" src="https://github.com/user-attachments/assets/cd7d6540-6808-4ff1-8f1d-d1764e087b45">

2024-09-17 12:14 UTC, johnnyomair commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    font-family: ${({ theme }) => theme.fontFamily};
> I think the Typography was originally not meant to render a tags like you do here, just span or p tags

Typography should be able to render all HTML tags. That's why we added the `component` prop.

We should investigate why the font family isn't correctly applied here.

2024-09-18 09:00 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    font-family: ${({ theme }) => theme.fontFamily};
Should we create a ticket for it? And should I leave the `font-family` style or remove it with the assumption that it will be fixed in the near future?

2024-09-18 10:15 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +export const FooterContentBlock = withPreview(
Thanks I updated the code so it cant happen 👍🏻

2024-09-18 10:15 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +        transform: translate(-50%, -50%);
Thanks I updated the code so it cant happen 👍🏻

2024-09-18 10:16 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +        place-self: start center;
nope i removed it

2024-09-24 10:56 UTC, johnnyomair commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                    {!!linkList.blocks.length && (
```suggestion
                    {!inkList.blocks.length > 0 && (
```

2024-09-24 10:57 UTC, johnnyomair commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    font-family: ${({ theme }) => theme.fontFamily};
Yes, please create a bug task for this.

> And should I leave the font-family style or remove it with the assumption that it will be fixed in the near future?

Both is fine with me. If you leave it, you could add a TODO

2024-09-25 13:44 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    font-family: ${({ theme }) => theme.fontFamily};
Done. I removed it

2024-09-25 13:46 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    font-family: ${({ theme }) => theme.fontFamily};
https://github.com/vivid-planet/comet-starter/pull/282/commits/13062c49df5aeb1c9edfedd00273ddfccfb797e4

2024-09-25 13:46 UTC, jomunker commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                    {!!linkList.blocks.length && (
https://github.com/vivid-planet/comet-starter/pull/282/commits/057812f6664bdf3186cda0ca93cf4fe06ae4d40a

2024-09-26 05:41 UTC, johnnyomair submitted a review, later dismissed

2024-09-26 06:59 UTC, mariokemetinger approved these changes

2024-09-26 07:26 UTC, thomasdax98 submitted a review, later dismissed

2024-09-26 07:27 UTC, jamesricky submitted a review, later dismissed

2024-09-26 07:30 UTC, SebiVPS submitted a review, later dismissed

2024-09-26 08:40 UTC, johnnyomair commented
I'd like to wait on @nsams' opinion here

2024-09-26 08:46 UTC, johnnyomair commented
@jomunker please resolve conflicts.

2024-09-26 09:31 UTC, jamesricky submitted a review, later dismissed

2024-09-27 11:53 UTC, nsams commented on api/src/common/blocks/link-list.block.ts
> +import { TextLinkBlock } from "@src/common/blocks/text-link.block";
```suggestion
import { TextLinkBlock } from "./text-link.block";
```
(you need to run eslint)

2024-09-27 12:37 UTC, nsams commented on admin/src/footers/EditFooterPage.tsx
> +                // @ts-expect-error type mismatch between createCompositeBlock and FooterContentBlockData, needs to be fixed in Comet
is there at least a ticket of this issue?

2024-09-27 14:05 UTC, jomunker commented on admin/src/footers/EditFooterPage.tsx
> +                // @ts-expect-error type mismatch between createCompositeBlock and FooterContentBlockData, needs to be fixed in Comet
@thomasdax98 Do you know that?

2024-09-27 14:06 UTC, jomunker commented on api/src/common/blocks/link-list.block.ts
> +import { TextLinkBlock } from "@src/common/blocks/text-link.block";
I think it is correct like it is 🤔

2024-09-30 09:22 UTC, johnnyomair commented on api/src/common/blocks/link-list.block.ts
> +import { TextLinkBlock } from "@src/common/blocks/text-link.block";
No, that should be relative, as both blocks are in `src/common/blocks`

2024-10-01 07:21 UTC, jomunker commented on api/src/common/blocks/link-list.block.ts
> +import { TextLinkBlock } from "@src/common/blocks/text-link.block";
https://github.com/vivid-planet/comet-starter/pull/282/commits/81283fb66252f7303c3c146d944050bfbfa7505b

2024-10-02 08:58 UTC, johnnyomair commented on api/src/footers/entities/footer.entity.ts
> +    @PrimaryKey({ columnType: "uuid" })
```suggestion
    @PrimaryKey({ type: "uuid" })
```

See #376

2024-10-07 12:32 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +    padding: ${({ theme }) => `60px ${theme.spacing.D100}`};
You should use the PageLayout here to achieve the same layout: https://github.com/vivid-planet/comet-starter/blob/fac2b23ce9ec5521e809d4a3813345cbd9c08c1f/site/src/layout/header/Header.tsx#L101

2024-10-08 09:36 UTC, SebiVPS commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                                    <LinkText component="span" variant="p200">
can be changed when https://github.com/vivid-planet/comet-starter/pull/384 is merged
https://github.com/vivid-planet/comet-starter/pull/384

2024-10-15 09:37 UTC, johnnyomair commented on site/src/documents/pages/blocks/FooterContentBlock.tsx
> +                    </ImageWrapper>
@jamesricky's idea sounds good. Created a task: https://vivid-planet.atlassian.net/browse/COM-1177.

2024-10-15 12:49 UTC, mariokemetinger approved these changes

2024-10-15 13:10 UTC, johnnyomair commented
@nsams please review

2024-10-22 16:13 UTC, nsams commented on admin/src/footers/EditFooterPage.tsx
> +                // @ts-expect-error type mismatch between createCompositeBlock and FooterContentBlockData, needs to be fixed in Comet
> Make copyrightNotice required in the API since we're saving an empty string anyway.

That sounds logical to me.

2024-10-24 08:30 UTC, SebiVPS commented on admin/src/footers/EditFooterPage.tsx
> +                // @ts-expect-error type mismatch between createCompositeBlock and FooterContentBlockData, needs to be fixed in Comet
Done 👍

2024-10-24 08:54 UTC, johnnyomair requested changes

2024-10-24 08:54 UTC, johnnyomair commented on api/src/footers/blocks/footer-content.block.ts
>      @BlockField({ nullable: true })
Please remove nullable: true here

2024-10-24 08:54 UTC, johnnyomair commented on api/src/footers/blocks/footer-content.block.ts
>      @BlockField({ nullable: true })
Please remove nullable: true here

2024-10-24 08:54 UTC, johnnyomair commented on api/src/footers/blocks/footer-content.block.ts
>      @IsUndefinable()
Please remove this validator

2024-10-24 09:24 UTC, johnnyomair approved these changes

2024-10-28 08:32 UTC, thomasdax98 approved these changes

2024-10-28 08:50 UTC, nsams approved these changes

2024-10-28 09:11 UTC, jamesricky approved these changes

2024-10-28 12:27 UTC, mariokemetinger approved these changes

2024-10-28 15:34 UTC, merged