Display linebreaks in RTE correctly
vivid-planet/comet-starter pull request #31
Opened 2023-10-20 06:27 UTC by juliawegmayr

Line breaks in the RTE block disappeared. To correctly display the text, a TextWrapper was implemented to set paragraph spaces.

2023-10-23 05:36 UTC, nsams commented
I'm not sure this is the best solution. Would replacing \n with `<br />` be an option?

2023-10-23 14:02 UTC, johnnyomair commented
I believe this should be done in the renderers, not with a wrapper.

> I'm not sure this is the best solution. Would replacing \n with `<br />` be an option?

We'd need `dangerouslySetInnerHTML` for this I suppose

2023-10-24 06:13 UTC, nsams commented
if done properly (ideally in our library) I wouldn't exclude dangerouslySetInnerHTML. If white-space: pre-line; is the best solution us that...

2023-10-25 06:09 UTC, juliawegmayr commented
I now applied the styling on the renderer. But I guess, I still need the styled-component here, as I don't know how to apply the pseudo:class otherwise.

2023-11-06 12:48 UTC, thomasdax98 commented
@nsams @johnnyomair @jamesricky Can you comment on this again?

2023-11-06 13:59 UTC, jamesricky commented
> if done properly (ideally in our library) I wouldn't exclude dangerouslySetInnerHTML. If white-space: pre-line; is the best solution, use that...

I think `white-space: pre-line;` is fine 🤷🏼

2023-11-06 14:03 UTC, johnnyomair requested changes

2023-11-06 14:03 UTC, johnnyomair commented on site/src/common/blocks/RichTextBlock.tsx
> +                <TextWrapper key={keys[idx]}>
Please don't add an additional div, replace the `p` tag with a `Paragraph` or `Unstyled` styled-component (`styled.p`)

2023-11-06 14:04 UTC, johnnyomair commented on site/src/common/blocks/RichTextBlock.tsx
> +    }
Why do you need this?

2023-11-08 12:38 UTC, juliawegmayr commented on site/src/common/blocks/RichTextBlock.tsx
> +    }
It's necessary if an empty paragraph is used to set spaces between paragraphs.

2023-11-15 10:48 UTC, nsams commented
Soft, I suppose

2023-11-15 12:05 UTC, johnnyomair commented on site/src/common/blocks/RichTextBlock.tsx
> +const StyledComponent = styled.p`
I'm not particularly fond of that naming. Maybe change it to `Text` instead?

2023-11-16 16:01 UTC, johnnyomair requested changes

2023-11-16 16:01 UTC, johnnyomair commented on site/src/common/blocks/RichTextBlock.tsx
> +    // Workaround empty paragraphs used as spacing
```suggestion
    // Workaround when empty paragraphs are used as "spacing" in content
```

2023-11-20 07:42 UTC, johnnyomair approved these changes

2023-11-20 07:44 UTC, johnnyomair commented
@nsams @jamesricky please review. Thanks!

2023-11-20 10:41 UTC, nsams approved these changes

2023-11-21 10:54 UTC, jamesricky approved these changes

2023-11-21 11:17 UTC, merged