Add scope to redirects
vivid-planet/comet-starter pull request #315
Opened 2024-07-29 17:34 UTC by jomunker

---

## PR Checklist

-   [x] Link to the respective task if one exists: COM-878
-   [ ] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>
    
</details>

2024-08-02 05:56 UTC, nsams submitted a review, later dismissed

2024-08-06 08:59 UTC, johnnyomair commented on api/src/db/migrations/Migration20240729171532.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
You'd need to drop all redirects before adding this non-nullable column. But wouldn't it be better to add it to the one migration we already have?

2024-08-06 08:59 UTC, johnnyomair commented on api/src/documents/pages/pages.module.ts
> +    imports: [MikroOrmModule.forFeature([Page]), RedirectsModule],
I don't think this import is needed

2024-08-06 08:59 UTC, johnnyomair commented on site/src/middleware.ts
> +import { domain } from "@src/config";
Please merge main and get the domain from the site config now that #283 has been merged

2024-08-06 08:59 UTC, johnnyomair commented on site/src/redirects/redirects.ts
> +    const key = `redirects-${JSON.stringify(scope)}`;
```suggestion
    const key = `redirects-${scope.domain}`;
```

2024-08-07 13:30 UTC, jomunker commented on api/src/db/migrations/Migration20240729171532.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
Why? It doesn't remove sth but just adds a column. Sure but that wouldn't make a difference for the first point right?

2024-08-07 14:45 UTC, johnnyomair commented on api/src/documents/pages/pages.module.ts
> +    imports: [MikroOrmModule.forFeature([Page]), RedirectsModule],
Remove it and see if the API still starts

2024-08-07 14:47 UTC, johnnyomair commented on api/src/db/migrations/Migration20240729171532.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
> Sure but that wouldn't make a difference for the first point right?

You're right.

> But wouldn't it be better to add it to the one migration we already have?

How ever, I'd still at this line to the initial migration, which should be fine for all new projects.

2024-08-08 06:58 UTC, jomunker commented on api/src/documents/pages/pages.module.ts
> +    imports: [MikroOrmModule.forFeature([Page]), RedirectsModule],
https://github.com/vivid-planet/comet-starter/pull/315/commits/712c7d6bcdfd9d2ae9dcbd73c86dd400f52ae9a1

2024-08-08 06:58 UTC, jomunker commented on api/src/db/migrations/Migration20240729171532.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
https://github.com/vivid-planet/comet-starter/pull/315/commits/e9a0bb4ae89507c158ee9f6bcdb7d9f2afcb9252

2024-08-08 10:43 UTC, johnnyomair commented on site/src/middleware.ts
> +    const scope = siteConfig?.scope.domain ? { domain: siteConfig?.scope.domain } : undefined;
You could get the scope after the if below, then you shouldn't need the undefined handling I suppose.

2024-08-13 06:46 UTC, dkarnutsch requested changes

2024-08-13 06:46 UTC, dkarnutsch commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
I don't think it is good practice to alter existing migrations. If the starter would be deployed, this change would not be made.

Create a new migration and also make it fail-safe by truncating the table before.

2024-08-13 11:34 UTC, jomunker commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
https://github.com/vivid-planet/comet-starter/pull/315#discussion_r1705171256
Please discuss this with @johnnyomair and let me know what I should do ^^

2024-08-13 11:47 UTC, johnnyomair commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
I'm sorry, this was my suggestion 😅 We did this multiple times in the past to avoid having a bunch of migrations when starting a new project. We could change our approach though

2024-09-09 15:00 UTC, jomunker commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
@dkarnutsch what do you prefer?

2024-09-09 15:01 UTC, jomunker commented on site/src/middleware.ts
> +    const scope = siteConfig?.scope.domain ? { domain: siteConfig?.scope.domain } : undefined;
https://github.com/vivid-planet/comet-starter/pull/315/commits/a6c7eb999732244667e62d7ff6612d677d86230f

2024-09-10 07:19 UTC, johnnyomair commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
@nsams what do you think? Maybe we should start adding actually working migrations once the Starter has been deployed

2024-09-20 04:06 UTC, nsams commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
A growing Number of Migrations in New Projects Is Not desirable, that is unnecessarily confusing.

Maybe we can drop database and run fixtures on every starter deploy?

2024-09-24 06:34 UTC, johnnyomair commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
@dkarnutsch what do you think?

2024-09-24 07:22 UTC, dkarnutsch commented on api/src/db/migrations/Migration20220721122758.ts
> +        this.addSql('alter table "Redirect" add column "scope_domain" text not null;');
@johnnyomair 
> Maybe we can drop database and run fixtures on every starter deploy?

I'm okay with that (out of scope for this PR)

2024-09-24 07:26 UTC, dkarnutsch submitted a review, later dismissed

2024-09-24 14:47 UTC, johnnyomair commented on site/src/middleware.ts
> +    if (scope) {
Why do you need this if? This will always be true

2024-09-24 14:47 UTC, johnnyomair commented on site/src/middleware.ts
> +async function createRewrites(scope: Pick<GQLRedirectScope, "domain">): Promise<RewritesMap> {
```suggestion
async function createRewrites(scope: GQLRedirectScope): Promise<RewritesMap> {
```

Pick shouldn't be necessary here.

2024-09-25 13:27 UTC, jomunker commented on site/src/middleware.ts
> +    if (scope) {
https://github.com/vivid-planet/comet-starter/pull/315/commits/6c2e52de285641c8dda7543f18254c0b982ea2cc

2024-09-25 13:27 UTC, jomunker commented on site/src/middleware.ts
> +async function createRewrites(scope: Pick<GQLRedirectScope, "domain">): Promise<RewritesMap> {
https://github.com/vivid-planet/comet-starter/pull/315/commits/7fb53030b9e33dfe2d8b7f4b6ff1be5dfd05cb34

2024-09-25 15:38 UTC, johnnyomair submitted a review, later dismissed

2024-09-25 15:56 UTC, nsams commented on site/src/redirects/redirects.ts
> +    const key = `redirects-${JSON.stringify(scope)}`;
I'd rather leave the JSON.stringify, less likely thinks break when scope parts change

2024-09-25 15:56 UTC, nsams submitted a review, later dismissed

2024-09-26 05:25 UTC, dkarnutsch approved these changes

2024-09-26 05:27 UTC, johnnyomair commented on site/src/redirects/redirects.ts
> +            ...Array.from(await createApiRedirects({ domain: scope.domain })),
```suggestion
            ...Array.from(await createApiRedirects(scope)),
```

2024-09-26 07:22 UTC, thomasdax98 submitted a review, later dismissed

2024-09-26 08:46 UTC, johnnyomair approved these changes

2024-09-26 08:46 UTC, merged