wrap stage block into a list block
vivid-planet/comet-starter pull request #332
Opened 2024-08-09 09:55 UTC by SebiVPS

wrap stage block into a list block, only one can be visible (prepare other stages which are not ready yet)
---

## PR Checklist

-   [x] Link to the respective task if one exists: COM-842
-   [x] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>
<img width="1812" alt="Screenshot 2024-08-09 at 11 53 04" src="https://github.com/user-attachments/assets/48f9860f-6799-4a07-94b8-ccd5e3cbc194">
</details>

2024-08-09 13:54 UTC, jamesricky approved these changes

2024-08-12 13:55 UTC, johnnyomair requested changes
As discussed, please change to a BlocksBlock

2024-08-13 08:38 UTC, SebiVPS commented
> As discussed, please change to a BlocksBlock

As discussed, a BlocksBlocks can not be used for only one block, i added the ListBlock with the BasicStageBlock and left a comment to use a BlocksBlock, when multiple stage blocks are needed.

2024-08-13 12:15 UTC, johnnyomair approved these changes

2024-08-14 11:50 UTC, jamesricky approved these changes

2024-08-16 05:33 UTC, merged