Improve favicons to add support for different browsers and use cases
vivid-planet/comet-starter pull request #340
Opened 2024-08-14 10:01 UTC by fichtnerma

---
Improve favicons to add support for different browsers and use cases

## PR Checklist

-   [ ] Link to the respective task if one exists: COM-1012
-   [ ] Provide screenshots/screencasts if the change contains visual changes

2024-08-14 11:54 UTC, johnnyomair requested changes

2024-08-14 11:54 UTC, johnnyomair commented on site/src/app/manifest.webmanifest
> +        { "src": "/icon-512.png", "type": "image/png", "sizes": "512x512" }
I just tested this locally, both these icons can't be found. Please make sure that this works.

2024-08-19 11:09 UTC, fichtnerma commented on site/src/app/manifest.webmanifest
> +        { "src": "/icon-512.png", "type": "image/png", "sizes": "512x512" }
It should work now

2024-09-09 11:31 UTC, johnnyomair commented
I just had a look at the article this PR is based on: https://evilmartians.com/chronicles/how-to-favicon-in-2021-six-files-that-fit-most-needs. Some parts are only required when making a PWA. Do we still want to support the PWA parts?

2024-09-09 12:26 UTC, nsams commented
> Some parts are only required when making a PWA

I don't know what a PWA exactly is, but having PWA compatible favicons - and nothing else - doesn't make it one. I'd keep it simple and only do things that actually solve problems.

Maybe the ones supported by [nextjs](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#image-files-ico-jpg-png) are enough.

2024-09-09 12:43 UTC, johnnyomair commented
> Maybe the ones supported by [nextjs](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons#image-files-ico-jpg-png) are enough.

Sounds good. @fichtnerma could you please remove the manifest and the icons in public/? Thanks!

2024-09-10 09:01 UTC, johnnyomair commented on site/src/middleware.ts
> +         * - manifest.json, manifest.webmanifest
```suggestion
         * - favicon.ico, icon.svg, apple-icon.png
         * - manifest.json
```

2024-09-10 09:02 UTC, johnnyomair approved these changes

2024-09-13 08:18 UTC, nsams commented
apple-icon is still needed even if there is a svg version of icon?

2024-09-13 08:43 UTC, fichtnerma commented
> apple-icon is still needed even if there is a svg version of icon?

Yes the apple-touch-icon is needed on iOS when placing the website on the Homescreen

2024-09-13 09:42 UTC, nsams commented
> Yes the apple-touch-icon is needed on iOS when placing the website on the Homescreen

and iOS really doesn't use the `<link rel="icon"` if there is no `<link rel="apple-touch-icon"`?

2024-09-16 12:07 UTC, fichtnerma commented
> > Yes the apple-touch-icon is needed on iOS when placing the website on the Homescreen
> 
> and iOS really doesn't use the `<link rel="icon"` if there is no `<link rel="apple-touch-icon"`?

Yeah without that icon there will just be no icon displayed

2024-09-17 07:10 UTC, nsams approved these changes

2024-09-24 08:03 UTC, merged