add desktop header styling
vivid-planet/comet-starter pull request #346
Opened 2024-08-28 08:18 UTC by SebiVPS

Add header styling according to comet starter figma design. Also take accessibility into consideration.

---

## PR Checklist

-   [x] Link to the respective task if one exists: COM-1046
-   [x] Provide screenshots/screencasts if the change contains visual changes

<details>
    <summary>Screenshots/screencasts</summary>

https://github.com/user-attachments/assets/27badde8-c294-4388-8245-ff2315a18266

</details>

2024-09-03 12:15 UTC, SebiVPS commented on site/src/layout/header/DesktopHeaderMenu.tsx
> +        text-decoration: underline ${({ theme }) => theme.palette.primary.main};
<img width="218" alt="Screenshot 2024-09-03 at 14 15 03" src="https://github.com/user-attachments/assets/76c7bbdf-021b-4878-8955-c7bd83b3f2ea">

2024-09-03 13:22 UTC, jamesricky approved these changes

2024-09-03 13:44 UTC, thomasdax98 approved these changes

2024-09-09 14:13 UTC, johnnyomair reviewed
Why do you add a DesktopHeaderMenu file? Is the mobile menu that different?

2024-09-09 14:13 UTC, johnnyomair commented on site/src/layout/header/DesktopHeaderMenu.sc.ts
This would be the first .sc.ts file in the Starter. Do we really want to promote this pattern? I don't think it's necessary to split the files here

2024-09-09 14:13 UTC, johnnyomair commented on site/src/layout/header/DesktopHeaderMenu.tsx
> +    header: GQLHeaderFragment[];
A component shouldn't use a fragment that it doesn't own. You'd need a DesktopHeaderMenu fragment here

2024-09-10 07:40 UTC, johnnyomair submitted a review, later dismissed

2024-09-10 07:41 UTC, johnnyomair requested changes

2024-09-10 07:41 UTC, johnnyomair commented on site/src/layout/header/Header.tsx
> +                                                    aria-label={`Submenu of ${node.name}`}
Please make the label translatable.

2024-09-10 08:03 UTC, SebiVPS commented on site/src/layout/header/Header.tsx
> +                                                    aria-label={`Submenu of ${node.name}`}
Done 👍

2024-09-10 12:44 UTC, johnnyomair approved these changes

2024-09-11 08:10 UTC, johnnyomair commented
@thomasdax98 @jamesricky please review, thanks!

2024-09-12 13:36 UTC, jamesricky approved these changes

2024-09-12 13:38 UTC, merged