Handle non-existing assets correctly
vivid-planet/comet-starter pull request #362
Opened 2024-09-16 12:22 UTC by fraxachun

Next will try to render a "normal" page when a non-existing asset (e.g. /assets/foo) is requested. This lead to misleading 500 errors as "assets" would be used as parameter for `/app/[domain]`, causing our site config setup to fail. To fix this, we add an additional page `/app/assets/[[...path]]` which always returns 404.

2024-09-17 07:06 UTC, nsams commented
couldn't you instead avoid the 500 by returning null (instead of throwing Error) and call `notFound()` in page.tsx if `getSiteConfigForDomain` returned null?

2024-09-17 11:49 UTC, johnnyomair reviewed
It's odd that this needs to be done in getSiteConfigForDomain, but I can't think of a better solution. We could try to get rid of the assets folder altogether, as we discussed in https://github.com/vivid-planet/comet-starter/pull/283#discussion_r1696577469.

2024-09-17 11:49 UTC, johnnyomair commented on site/src/util/siteConfig.ts
> +    if (domain === "assets") {
We should add a comment here explaining why this if is needed.

2024-09-24 06:32 UTC, johnnyomair commented on site/src/util/siteConfig.ts
> +        // /assets paths they are not handled by middleware.ts, therefore no rewriting has taken place and we cannot rely on params.domain
```suggestion
        // /assets paths are not handled by the middleware, therefore no rewriting has taken place and we cannot rely on params.domain
```

2024-10-02 14:56 UTC, thomasdax98 submitted a review, later dismissed

2024-10-03 09:58 UTC, johnnyomair requested changes
As discussed yesterday, please change this to a not found page in `src/app/assets/[[...path]]/page.tsx`

2024-10-04 05:35 UTC, nsams approved these changes

2024-10-07 10:25 UTC, johnnyomair approved these changes

2024-10-07 10:25 UTC, merged

2025-04-22 11:14 UTC, johnnyomair commented
Remove the recommended-change label since this should be done like in https://github.com/vivid-planet/comet-starter/pull/748 instead.