Add `@AffectedEntity` to link query
vivid-planet/comet-starter pull request #393
Opened 2024-10-14 08:06 UTC by thomasdax98

2024-10-14 13:11 UTC, dkarnutsch approved these changes

2024-10-14 16:08 UTC, nsams approved these changes

2024-10-15 05:57 UTC, johnnyomair requested changes

2024-10-15 05:57 UTC, johnnyomair commented on api/src/documents/links/links.resolver.ts
> +    async link(@Args("id", { type: () => ID }) id: string): Promise<Link | null> {
This should cause changes in the schema.gql.

2025-01-10 10:14 UTC, johnnyomair commented
Replaced with #642.

2025-01-10 10:14 UTC, closed without merging