Site: Move resolving of redirects from middleware to ...path page
vivid-planet/comet-starter pull request #513
Opened 2024-11-13 08:13 UTC by nsams

This has better performance as we don't have to load all redirects into memory.

Demo implementation: https://github.com/vivid-planet/comet/pull/2638

The /admin redirect in #2638 is broken (when deployed), leave that in middleware to be able to access env var

2024-11-13 10:11 UTC, johnnyomair commented on site/src/app/[domain]/[language]/[[...path]]/page.tsx
> +    const skipPage = !siteConfig.scope.languages.includes(params.language);
Should we add a comment explaining this? Or do you think it's obvious enough?

2024-11-13 10:40 UTC, nsams commented on site/src/app/[domain]/[language]/[[...path]]/page.tsx
> +    const skipPage = !siteConfig.scope.languages.includes(params.language);
yes, this is not very obvious

maybe something like that?
```suggestion
    const skipPage = !siteConfig.scope.languages.includes(params.language); // redirects are not language scoped, language is invalid we still need to load them (and skip pages)
```

2024-12-09 10:14 UTC, thomasdax98 approved these changes

2024-12-16 09:04 UTC, nsams commented on site/src/app/[domain]/[language]/[[...path]]/page.tsx
> +    const skipPage = !siteConfig.scope.languages.includes(params.language);
```suggestion
    // Redirects are scoped by domain only, not by language.
    // If the language param isn't a valid language, it may still be the first segment of a redirect source.
    // In that case we skip resolving page and only check if the path is a redirect source.
    const skipPage = !siteConfig.scope.languages.includes(params.language);
```

2024-12-16 13:32 UTC, johnnyomair submitted a review, later dismissed

2024-12-16 13:32 UTC, johnnyomair requested changes
Please resolve conflicts

2024-12-17 15:56 UTC, nsams commented on site/src/app/[domain]/[language]/[[...path]]/page.tsx
> +                            destination = `${(internalLink.targetPage.scope as GQLPageTreeNodeScope).language}/${internalLink.targetPage.path}`;
```suggestion
                            destination = `/${(internalLink.targetPage.scope as GQLPageTreeNodeScope).language}/${internalLink.targetPage.path}`;
```

2024-12-18 09:20 UTC, johnnyomair approved these changes

2024-12-18 09:51 UTC, thomasdax98 approved these changes

2024-12-18 09:51 UTC, merged