Use consistent root for serving admin
vivid-planet/comet-starter pull request #588
Opened 2024-12-04 12:17 UTC by dkarnutsch

Currently it makes a difference from which directory the server is called.

This works
```
➜  ~/ws/comet-starter/admin/server git:(main) ✗ APP_PORT=3001 node index.js       
Current working directory: /Users/danielkarnutsch/ws/comet-starter/admin/server
Admin app listening at http://localhost:3001
```

while this is not working:
```
➜  ~/ws/comet-starter/admin git:(main) ✗ APP_PORT=3001 node server/index.js
Current working directory: /Users/danielkarnutsch/ws/comet-starter/admin
node:fs:441
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '../build/index.html'
```

With this PR the admin is always served relative to the location of `server.js`. Furthermore `server.js` was renamed to `index.js` to make it possible to run the server using `node server` instead of using `node server/server.js`.

2024-12-04 17:10 UTC, nsams commented
yes, it is strange that the server serves cwd/../build

wouldn't it make more sense to serve cwd or cwd/build?

2024-12-05 14:06 UTC, johnnyomair reviewed
> wouldn't it make more sense to serve cwd or cwd/build?

I'd also do this.

2025-01-09 17:12 UTC, johnnyomair approved these changes

2025-01-10 10:16 UTC, thomasdax98 submitted a review, later dismissed

2025-01-10 10:22 UTC, manuelblum approved these changes

2025-01-10 10:39 UTC, johnnyomair commented
@dkarnutsch please open a PR for Demo as well, thanks!

2025-01-13 13:10 UTC, dkarnutsch commented on admin/server/index.js
> +    express.static(path.join(currentWorkingDirectory, "./build"), {
@nsams done with [d78f9ef](https://github.com/vivid-planet/comet-starter/commit/d78f9effa809c8512c75d29087575e08792bdf14)

2025-01-13 13:27 UTC, dkarnutsch commented
> Needs a PR in Demo.

https://github.com/vivid-planet/comet/pull/3098

2025-01-14 10:31 UTC, nsams approved these changes

2025-01-14 10:44 UTC, johnnyomair approved these changes

2025-01-14 10:44 UTC, johnnyomair requested changes
The lint workflow is failing.

2025-01-14 13:33 UTC, dkarnutsch commented
> The lint workflow is failing.

@johnnyomair due to a knip issue (cc @manuelblum), fixed with https://github.com/vivid-planet/comet-starter/pull/588/commits/359d4c00a7341e3991f0cbc8ba5102e4e1c10159

2025-01-14 14:56 UTC, manuelblum approved these changes

2025-01-14 14:58 UTC, merged