Fix error handling for non-existing API routes
vivid-planet/comet-starter pull request #622
Opened 2024-12-18 14:54 UTC by fraxachun

## Description

Previously, URLs starting with `/api/` were ignored by the middleware because we didn't need the domain parameter in the API routes. However, this lead to errors when calling a non-existing API route because the `not-found.tsx` page relies on the domain parameter. We fix this by moving API routes into the domain folder and no longer ignore them in the middleware.

Reflects https://github.com/vivid-planet/comet/pull/3086 for the Starter.

2024-12-19 13:37 UTC, nsams commented
can't you create a `not-found.tsx` file in `/api/` instead of the catchall route?

2024-12-31 09:41 UTC, thomasdax98 approved these changes

2025-01-09 16:23 UTC, johnnyomair commented
> > can't you create a `not-found.tsx` file in `/api/` instead of the catchall route?
> 
> That doesn't work.

I believe this is related to Next always rendering not-found.js, even when it's not used: https://github.com/vercel/next.js/issues/53252#issuecomment-1694513068.

2025-01-09 16:24 UTC, johnnyomair approved these changes

2025-01-10 07:58 UTC, dkarnutsch approved these changes

2025-01-10 07:58 UTC, dkarnutsch commented
I'd add recommended-change

2025-01-10 10:22 UTC, manuelblum approved these changes

2025-01-10 10:45 UTC, johnnyomair requested changes
Needs a PR in Demo.

2025-01-12 18:26 UTC, nsams commented
I propose a different solution for this issue: https://github.com/vivid-planet/comet/pull/3086

2025-01-14 15:13 UTC, johnnyomair approved these changes

2025-01-14 15:14 UTC, johnnyomair commented
General question: If a PR change significantly during review, should we update the PR's title and description? What is the best for future reference?

2025-01-14 17:11 UTC, nsams submitted a review, later dismissed

2025-01-15 07:06 UTC, dkarnutsch approved these changes

2025-01-16 08:00 UTC, johnnyomair commented
> > General question: If a PR change significantly during review, should we update the PR's title and description? What is the best for future reference?
> 
> Should be updated, especially when it is used in the commit message. My bad.

I've updated the description to the new solution.

2025-01-24 11:52 UTC, thomasdax98 approved these changes

2025-01-27 06:36 UTC, manuelblum approved these changes

2025-01-27 08:06 UTC, johnnyomair requested changes
Conflicts need to be fixed.

2025-01-27 11:19 UTC, nsams approved these changes

2025-01-27 11:26 UTC, johnnyomair approved these changes

2025-01-27 11:26 UTC, merged