Copy createCometApp from GitLab
vivid-planet/comet-starter pull request #8
Opened 2023-08-11 11:46 UTC by max-debug022

# Crate Comet App :comet: 

Example Terminal output:

![Screenshot_2023-07-28_at_12.40.16](/uploads/1da89b4030b9f41b22bd428eed392e9c/Screenshot_2023-07-28_at_12.40.16.png)

![Screenshot_2023-07-28_at_12.42.16](/uploads/2204c02fee444cd9db08e841baa1c820/Screenshot_2023-07-28_at_12.42.16.png)

![Screenshot_2023-07-18_at_12.22.07](/uploads/28a09f4ab66584363cf1e46d54026df6/Screenshot_2023-07-18_at_12.22.07.png)

![Screenshot_2023-07-18_at_12.22.19](/uploads/269f93b9f142cc19ccb8b933a4094b43/Screenshot_2023-07-18_at_12.22.19.png)

**README**
# create-comet-app

This is a command-line tool to create a new Comet app. It sets up a project with the necessary configuration and files
to get started quickly.

## Usage

To create a new Comet app, run the following command:

```
npx create-comet-app
```

### Arguments

The following arguments can be passed to customize the project setup:

- `project-name` (required*): Specifies the name of the project. It will be used as the directory name for the project.
- `--no-showcase` (required*): Disables the addition of showcase content in the project.
- `--showcase` (required*): Adds showcase content to the project.
- `-v` or `--verbose`: Enables extra console logs for verbose output.
- `-V` or `--version`: Outputs the version number.
- `-h` or `--help`: Display help for the command.

*If you choose not to provide a required argument, you will be prompted to enter it during the setup process.

Example usage with arguments:

```
npx create-comet-app my-project --add-showcase -v
```

This command will create a new Comet app with the name "my-project", include showcase content, and enable verbose output
in the console logs.

2023-08-22 09:03 UTC, nsams commented on create-comet-app/src/util/createWorkingDirectoryCopy.ts
> +        process.exit(1);
Please don't do process.exit somewhere in business code

And this whole Promise construct (that you catch in the same function) is a bit strange

2023-08-22 09:03 UTC, nsams commented on create-comet-app/src/util/removeShowcaseContent.ts
> +                    .then((lintedFileContent) => {
why not await?

2023-08-22 09:03 UTC, nsams commented on create-comet-app/src/util/replacePlaceholder.ts
> +    const value = projectName;
projectName is such a good variable name, why do you use not-so-much meaning name value?

2023-08-31 12:50 UTC, johnnyomair reviewed
Please move the script into a `create-app` folder, as we don't call it create-comet-app

2023-08-31 12:50 UTC, johnnyomair commented on create-comet-app/src/createCometApp.ts
> +    console.log(kleur.white(`Creating a new comet app in `) + kleur.yellow(`${process.cwd()}\n`));
```suggestion
    console.log(kleur.white(`Creating a new Comet app in `) + kleur.yellow(`${process.cwd()}\n`));
```

2023-08-31 12:50 UTC, johnnyomair commented on create-comet-app/src/util/validateNodeVersion.ts
> +    return major > 18 || (major === 18 && minor >= 0);
```suggestion
    return major >= 18;
```

2023-09-11 13:47 UTC, dkarnutsch commented
From testing:
- .github/workflows should be removed once set up

2023-09-12 13:47 UTC, dkarnutsch requested changes

2023-09-12 13:47 UTC, dkarnutsch commented on create-comet-app/src/util/validateNodeVersion.ts
> +}
this constraint should be specified in package.json

with https://docs.npmjs.com/cli/v10/using-npm/config#engine-strict this might not be necessary at all

2023-09-12 13:47 UTC, dkarnutsch commented on create-comet-app/src/util/createInitialGitCommit.ts
> +export async function createInitialGitCommit() {
might use https://github.com/steveukx/git-js instead of calling git on your own

2023-09-12 16:08 UTC, nsams commented on create-comet-app/src/util/createInitialGitCommit.ts
> +export async function createInitialGitCommit() {
I wouldn't change that. No real benefit for those very basic actions imho

2023-09-13 06:40 UTC, max-debug022 commented on create-comet-app/README.md
> +- `--showcase` (required*): Adds showcase content to the project.
Thank you, I forgot to change that since the user is not prompted to enter it if not provided.

2023-09-13 07:32 UTC, max-debug022 commented on create-comet-app/src/util/validateNodeVersion.ts
> +}
Doesnt [engine-strict](https://docs.npmjs.com/cli/v10/using-npm/config#engine-strict) only prohibit installing? This validation is necessary for the replaceAll function.

2023-09-14 07:45 UTC, nsams commented on .prettierignore
> +create-comet-app/
you renamed that to create-app; but why do you have it in here at all?

2023-09-14 07:46 UTC, nsams commented on create-app/README.md
> +*If you choose not to provide a required argument, you will be prompted to enter it during the setup process.
remove that outdated line

2023-09-14 07:46 UTC, nsams commented on create-app/package.json
> +  "bin": {
still 2 spaces, please change to 4

2023-09-20 16:57 UTC, nsams approved these changes

2023-09-21 08:03 UTC, johnnyomair commented on .prettierignore
> -api/uploads/
This line should not be deleted, otherwise header files (which are JSON) will be checked using Prettier on commit, which is not necessary

2023-09-21 08:03 UTC, johnnyomair commented on create-app/.eslintrc.json
> +    "extends": ["@comet/eslint-config/nestjs"]
We could add a separate `@comet/eslint-config/node` in the future

2023-09-21 08:04 UTC, johnnyomair commented on create-app/README.md
> +npx @comet/create-app my-project -v
I think we should show an example output here

2023-09-21 08:05 UTC, johnnyomair commented on create-app/README.md
> +- `-h` or `--help`: Display help for the command.
Do you plan to add the `--no-install, --ni` (as discussed internally) in this PR?

2023-09-21 08:07 UTC, johnnyomair commented on create-app/src/createCometApp.ts
> +    if (!validateNodeVersion()) {
This function should be called `isValidNodeVersion()` IMO, as the actual "validation" (= the early return) happens outside the function.

2023-09-21 08:07 UTC, johnnyomair commented on create-app/src/createCometApp.ts
> +    program.name(name).description("CLI to create a comet app").version(version);
```suggestion
    program.name(name).description("CLI to create a Comet app").version(version);
```

2023-09-21 08:09 UTC, johnnyomair commented on create-app/src/util/replacePlaceholder.ts
> +            console.log(kleur.yellow(`Could not replace Placeholder in ${file}`));
```suggestion
            console.log(kleur.yellow(`Could not replace placeholder in ${file}`));
```

2023-09-21 08:11 UTC, max-debug022 commented on .prettierignore
> -api/uploads/
but isnt this file already covered in api/.prettierignore?

2023-09-21 10:25 UTC, max-debug022 commented on .prettierignore
> -api/uploads/
Shouldn't this already be covered by `api/` in line 3?

2023-09-21 13:47 UTC, johnnyomair commented on .prettierignore
> -api/uploads/
Yes, but when using Prettier directly in the api/ folder, files in the uploads/ folder get formatted. Could you please add it to api/.prettierignore instead?

2023-09-21 13:52 UTC, johnnyomair approved these changes
Please wait for all reviewers to approve at least once. Then I think we should squash-merge this PR 🙂

2023-09-21 16:09 UTC, nsams submitted a review, later dismissed

2023-09-25 13:26 UTC, johnnyomair submitted a review, later dismissed

2023-09-25 14:15 UTC, dkarnutsch submitted a review, later dismissed

2023-09-27 07:24 UTC, nsams commented on .prettierignore
> +create-app/README.md
- if you place it here in the root it will be part of every app
- why prettierignore readme at all?

2023-09-27 07:25 UTC, nsams commented on create-app/package.json
> +        "ts-node": "^10.9.1"
I think you don't need ts-node as dependency, not even as dev-dependency?

2023-09-27 07:33 UTC, nsams commented on create-app/package.json
> +        "eslint-plugin-unused-imports": "^0.1.3",
please clenaup devDependencies

- remove @types/prompts
- remove all eslint packages that you don't use directly (@comet/eslint-config alone should be enough)
- eslint package is not a devDependency as you need it at runtime. what about plugins and configs?

2023-09-29 13:42 UTC, nsams approved these changes

2023-10-02 07:38 UTC, dkarnutsch submitted a review, later dismissed

2023-10-04 13:41 UTC, fraxachun commented
The no-install flag does not work, at least with my tests. It always skips this step.

2023-10-04 13:42 UTC, fraxachun commented
Please add instructions in readme on how to develop and publish this module.

2023-10-05 06:02 UTC, johnnyomair commented
> Please add instructions in readme on how to develop and publish this module.

I will add publishing in a follow-up release. My idea is to automatically publish a minor version on every change in `create-app/*`, similar to `@comet/upgrade`. Do you think this is a good idea?

2023-10-05 10:27 UTC, max-debug022 commented
> The no-install flag does not work, at least with my tests. It always skips this step.
I have tested it and both `-ni` and `--no-install` worked as intended.

2023-10-05 12:05 UTC, nsams commented
did you also test without the flag?

2023-10-05 13:53 UTC, johnnyomair submitted a review, later dismissed

2023-10-05 15:16 UTC, nsams submitted a review, later dismissed

2023-10-09 08:47 UTC, johnnyomair commented on create-app/tsconfig.json
> +            "@util/*": ["src/util/*"],
We don't have this alias

2023-10-10 06:42 UTC, nsams approved these changes

2023-10-10 06:57 UTC, johnnyomair commented on create-app/README.md
> +    bash npm start
```suggestion
    ```bash
    npm start
```

Maybe I want to use zsh? 😉

2023-10-10 06:57 UTC, johnnyomair commented on create-app/tsconfig.json
> +        "rootDirs": ["src/", "./"],
```suggestion
```
I don't think we need this option

2023-10-10 06:57 UTC, johnnyomair commented on create-app/tsconfig.json
> +        "jsx": "react",
```suggestion
```

We're not using React in this tool

2023-10-10 06:57 UTC, johnnyomair commented on create-app/tsconfig.json
> +        "exactOptionalPropertyTypes": true
It seems to me that you're randomly adding settings to TS config. Some may be good, others we may not need at all. Why not use the [Node 18 base](https://www.typescriptlang.org/docs/handbook/tsconfig-json.html#tsconfig-bases) as a start and _only_ add the settings we definitely need?

And: We should unify the TS configs across all Comet packages (out of scope) IMO.

2023-10-10 06:59 UTC, johnnyomair commented
Running npm install in the create-app folder leads to package-lock.json changes. Please fix that

2023-10-10 07:00 UTC, johnnyomair commented
Running `npm run build` adds new files that are not ignored:

<img width="304" alt="image" src="https://github.com/vivid-planet/comet-starter/assets/48853629/32ef708f-65e4-437f-8ef0-a7527e462a97">

Also, package.json and the src/ folder shouldn't be in lib/. This is presumably to a wrong configuration in TS config

2023-10-10 07:21 UTC, johnnyomair commented
The bin/index.js is not executable: `chmod +x bin/index.js`

For your info: You can test a close to production usage of the tool by calling `npm link` in the create-app/ directory. Then you may try `npx @comet/create-app`

2023-10-10 07:41 UTC, johnnyomair commented on create-app/package.json
> +    },
```suggestion
    "bin": "./bin/index.js",
```

2023-10-10 07:41 UTC, johnnyomair commented on create-app/package.json
> +        "bin/**/*.js",
```suggestion
        "bin/index.js",
```

2023-10-16 09:20 UTC, max-debug022 commented
> The bin/index.js is not executable: `chmod +x bin/index.js`
> 
> For your info: You can test a close to production usage of the tool by calling `npm link` in the create-app/ directory. Then you can use `npx @comet/create-app`

Thank you for this hint!

2023-10-16 09:43 UTC, max-debug022 commented on create-app/tsconfig.json
> +        "exactOptionalPropertyTypes": true
Using Node18 base is a good idea. Nevertheless, I did not randomly add settings. I mostly used recommended settings as documented in https://www.typescriptlang.org/tsconfig.

2023-10-16 14:33 UTC, fraxachun commented on create-app/tsconfig.json
> +        "exactOptionalPropertyTypes": true
> Option 'exactOptionalPropertyTypes' cannot be specified without specifying option 'strictNullChecks'.ts

2023-10-16 14:33 UTC, fraxachun commented on create-app/src/createApp.ts
> +        installProjectPackages();
> .git can't be found (see https://git.io/Jc3F9)
> npm ERR! code 1
> npm ERR! path /Users/franz/dev/test
> npm ERR! command failed
> npm ERR! command sh -c husky install

I think you have to execut `git init` first.

2023-10-18 13:39 UTC, max-debug022 commented
> The description of the PR should be added to the Readme of the project

I dont understand what you mean. The description of this PR is based on the README. Or do you mean the images?

2023-10-23 11:13 UTC, fraxachun commented
> I dont understand what you mean. The description of this PR is based on the README. Or do you mean the images?

You're right, i mixed up the directories.

2023-10-23 11:46 UTC, fraxachun commented on create-app/src/util/createInitialGitCommit.ts
> +export function createInitialGitCommit() {
This is not called anywhere.

2023-10-23 11:56 UTC, max-debug022 commented on create-app/src/util/createInitialGitCommit.ts
> +export function createInitialGitCommit() {
Thanks I deleted the function call by mistake

2023-10-30 07:21 UTC, max-debug022 commented
@nsams @johnnyomair @fraxachun could you please review/approve this pr again?

2023-10-30 07:58 UTC, nsams approved these changes

2023-10-30 12:48 UTC, johnnyomair requested changes

2023-10-30 12:48 UTC, johnnyomair commented on create-app/src/util/replacePlaceholder.ts
> +                if (file.endsWith("intl-update.sh")) fs.writeFileSync(file, contents.replaceAll("lang/starter-lang", `lang/${projectName}-lang`));
IMO this if should be before the  placeholder.test if, as there's no need to check if the file contains starter (we already know that it does)

2023-10-30 12:48 UTC, johnnyomair commented on create-app/tsconfig.json
> +        "lib": ["es2022"],
```suggestion
```

This should not be needed, as there's already a never version in the base: https://github.com/tsconfig/bases/blob/main/bases/node18.json#L8

2023-10-30 12:48 UTC, johnnyomair commented on create-app/tsconfig.json
> +        "baseUrl": "./",
This config option is not recommended for Node environments: https://www.typescriptlang.org/tsconfig#baseUrl

2023-10-30 12:48 UTC, johnnyomair commented on create-app/tsconfig.json
> +{
This should be enough for our use case

```json
{
    "extends": "@tsconfig/node18/tsconfig.json",
    "compilerOptions": {
        "rootDir": "src/",
        "outDir": "lib/"
    },
    "include": ["src/**/*"]
}
```

2023-10-30 12:48 UTC, johnnyomair commented on create-app/src/util/createWorkingDirectoryCopy.ts
> +    const clone = `git clone --depth 1 git@github.com:vivid-planet/comet-starter.git ./${projectName}`;
Please use a HTTPS clone for this

2023-10-30 12:48 UTC, johnnyomair commented on create-app/src/createApp.ts
> +const name = require("../package.json").name;
This should fail in lint. Please add create-app/ to the lint setup (lint-staged and ESLint)

2023-10-30 12:48 UTC, johnnyomair commented on create-app/src/createApp.ts
> +const name = require("../package.json").name;
And this could also be like this `const { name, version } = require("../package.json");`

2023-10-30 13:15 UTC, max-debug022 commented on create-app/src/util/replacePlaceholder.ts
> +                if (file.endsWith("intl-update.sh")) fs.writeFileSync(file, contents.replaceAll("lang/starter-lang", `lang/${projectName}-lang`));
We came to the conclusion that we leave it as it is.

2023-10-31 08:25 UTC, johnnyomair requested changes

2023-10-31 08:25 UTC, johnnyomair commented on create-app/src/createApp.ts
> +        createInitialGitCommit();
This call should be before creating the spinner. Otherwise the output looks like this:

<img width="712" alt="image" src="https://github.com/vivid-planet/comet-starter/assets/48853629/890b678a-bfd0-4cca-8e81-8e1eecb1d985">

2023-10-31 08:25 UTC, johnnyomair commented on create-app/src/createApp.ts
> +        createInitialGitCommit();
Also, it doesn't create a commit when using the option `--no-install`

2023-10-31 08:30 UTC, johnnyomair commented
@max-debug022 please adapt the PR's description so it can be used as the commit message of the squashed commit?

2023-10-31 08:30 UTC, johnnyomair commented on create-app/package.json
> +    "devDependencies": {
The package should have TypeScript v5 as dev dependency. Thanks @kaufmo for noticing!

2023-10-31 08:52 UTC, max-debug022 commented on create-app/src/createApp.ts
> +        createInitialGitCommit();
Thats true thanks

2023-10-31 09:01 UTC, johnnyomair submitted a review, later dismissed

2023-10-31 16:21 UTC, nsams commented on lint-staged.config.js
> +    "create-app/**/*.{ts,tsx}": () => "npm --prefix create-app run lint:tsc",
if you add those lines (are they really required?) you have to remove them in create-app again...

2023-10-31 16:24 UTC, nsams commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
for future improvements:
this now logs everything after install finished, better would be to stream output while process is running (as this one is running quite long, and itself has progress output)

2023-11-02 06:14 UTC, max-debug022 commented on lint-staged.config.js
> +    "create-app/**/*.{ts,tsx}": () => "npm --prefix create-app run lint:tsc",
No those lines are not required for the code but aren't necessary for the pre-commit hook?

2023-11-02 07:06 UTC, fraxachun requested changes

2023-11-02 07:15 UTC, fraxachun commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
I would skip this step at all.

- It takes very long
- Outputting doesn't work (neither streamed nor after finishing)
- Interrupting leaves you with the child processes still running
- Executing install.sh is a common task for every developer

2023-11-02 09:55 UTC, nsams commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
everything correct.

The agument for doing the install is that others (create-next-app, create-react-app) also do the install step.

Personally, I don't care :)

2023-11-02 09:58 UTC, nsams commented on lint-staged.config.js
> +    "create-app/**/*.{ts,tsx}": () => "npm --prefix create-app run lint:tsc",
Of course we want to lint everything including create-app. The lint pipeline doesn't use lint-staged though (i think) - if that is correct you might not need it here - if you can accept that pre-commit hook doesn't lint create-app.

Or, you simply remove those lines during project setup

2023-11-02 14:04 UTC, fraxachun commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
If you don't want to delete it, use `{ stdio: "inherit" }` to stream the output. However, I don't know how to interrupt it.

2023-11-08 16:44 UTC, nsams submitted a review, later dismissed

2023-11-15 07:10 UTC, fraxachun approved these changes

2023-11-15 07:14 UTC, dkarnutsch approved these changes

2023-11-15 07:22 UTC, johnnyomair commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
> Interrupting leaves you with the child processes still running

IMO this should be fixed asap

2023-11-15 07:23 UTC, nsams commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
the simplest fix would be to remove it

2023-11-15 07:29 UTC, johnnyomair approved these changes

2023-11-15 07:36 UTC, fraxachun commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
As I already stated, I'm for removing.

2023-11-15 07:36 UTC, johnnyomair commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
Do we need to decide this now, or do it in a follow-up PR?

2023-11-15 07:41 UTC, johnnyomair requested changes
Please remove installing the dependencies, as it doesn't work properly.

This includes
- Removing the `--no-install` option
- Changing the final output to suggest executing `./install.sh`

2023-11-15 07:42 UTC, johnnyomair commented on create-app/src/util/installProjectPackages.ts
> +        if (verbose) console.log(kleur.white(stdout.toString()));
I'd rather remove it than having a solution that doesn't work properly.

2023-11-16 07:08 UTC, nsams submitted a review, later dismissed

2023-11-16 07:43 UTC, johnnyomair approved these changes

2023-11-16 07:45 UTC, johnnyomair requested changes

2023-11-16 07:45 UTC, johnnyomair commented on create-app/src/createApp.ts
> +    console.log(kleur.white(`nvm use\n`));
Please add "Run ./install.sh" or similar here

2023-11-16 07:59 UTC, johnnyomair approved these changes

2023-11-16 08:04 UTC, merged